// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: novonotes/audio_engine/v1alpha1/engine_management.proto
// Protobuf C++ Version: 5.28.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/message.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto

namespace google
{
namespace protobuf
{
namespace internal
{
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct
    TableStruct_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto
{
    static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto;
namespace novonotes
{
namespace audio_engine
{
namespace v1alpha1
{
class InitializeRequest;
struct InitializeRequestDefaultTypeInternal;
extern InitializeRequestDefaultTypeInternal
    _InitializeRequest_default_instance_;
class InitializeResponse;
struct InitializeResponseDefaultTypeInternal;
extern InitializeResponseDefaultTypeInternal
    _InitializeResponse_default_instance_;
class PlayTestToneRequest;
struct PlayTestToneRequestDefaultTypeInternal;
extern PlayTestToneRequestDefaultTypeInternal
    _PlayTestToneRequest_default_instance_;
class PlayTestToneResponse;
struct PlayTestToneResponseDefaultTypeInternal;
extern PlayTestToneResponseDefaultTypeInternal
    _PlayTestToneResponse_default_instance_;
class ResetStateRequest;
struct ResetStateRequestDefaultTypeInternal;
extern ResetStateRequestDefaultTypeInternal
    _ResetStateRequest_default_instance_;
class ResetStateResponse;
struct ResetStateResponseDefaultTypeInternal;
extern ResetStateResponseDefaultTypeInternal
    _ResetStateResponse_default_instance_;
class ShutdownRequest;
struct ShutdownRequestDefaultTypeInternal;
extern ShutdownRequestDefaultTypeInternal _ShutdownRequest_default_instance_;
class ShutdownResponse;
struct ShutdownResponseDefaultTypeInternal;
extern ShutdownResponseDefaultTypeInternal _ShutdownResponse_default_instance_;
}  // namespace v1alpha1
}  // namespace audio_engine
}  // namespace novonotes
namespace google
{
namespace protobuf
{}  // namespace protobuf
}  // namespace google

namespace novonotes
{
namespace audio_engine
{
namespace v1alpha1
{

// ===================================================================

// -------------------------------------------------------------------

class ShutdownResponse final
    : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:novonotes.audio_engine.v1alpha1.ShutdownResponse)
 */
{
   public:
    inline ShutdownResponse() : ShutdownResponse(nullptr) {}
    template <typename = void>
    explicit PROTOBUF_CONSTEXPR ShutdownResponse(
        ::google::protobuf::internal::ConstantInitialized);

    inline ShutdownResponse(const ShutdownResponse& from)
        : ShutdownResponse(nullptr, from)
    {}
    inline ShutdownResponse(ShutdownResponse&& from) noexcept
        : ShutdownResponse(nullptr, std::move(from))
    {}
    inline ShutdownResponse& operator=(const ShutdownResponse& from)
    {
        CopyFrom(from);
        return *this;
    }
    inline ShutdownResponse& operator=(ShutdownResponse&& from) noexcept
    {
        if(this == &from) return *this;
        if(GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
           && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
        )
        {
            InternalSwap(&from);
        }
        else
        {
            CopyFrom(from);
        }
        return *this;
    }

    inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
        ABSL_ATTRIBUTE_LIFETIME_BOUND
    {
        return _internal_metadata_
            .unknown_fields<::google::protobuf::UnknownFieldSet>(
                ::google::protobuf::UnknownFieldSet::default_instance);
    }
    inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
        ABSL_ATTRIBUTE_LIFETIME_BOUND
    {
        return _internal_metadata_
            .mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
    }

    static const ::google::protobuf::Descriptor* descriptor()
    {
        return GetDescriptor();
    }
    static const ::google::protobuf::Descriptor* GetDescriptor()
    {
        return default_instance().GetMetadata().descriptor;
    }
    static const ::google::protobuf::Reflection* GetReflection()
    {
        return default_instance().GetMetadata().reflection;
    }
    static const ShutdownResponse& default_instance()
    {
        return *internal_default_instance();
    }
    static inline const ShutdownResponse* internal_default_instance()
    {
        return reinterpret_cast<const ShutdownResponse*>(
            &_ShutdownResponse_default_instance_);
    }
    static constexpr int kIndexInFileMessages = 3;
    friend void swap(ShutdownResponse& a, ShutdownResponse& b) { a.Swap(&b); }
    inline void Swap(ShutdownResponse* other)
    {
        if(other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
        if(GetArena() != nullptr && GetArena() == other->GetArena())
        {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
        if(GetArena() == other->GetArena())
        {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
            InternalSwap(other);
        }
        else
        {
            ::google::protobuf::internal::GenericSwap(this, other);
        }
    }
    void UnsafeArenaSwap(ShutdownResponse* other)
    {
        if(other == this) return;
        ABSL_DCHECK(GetArena() == other->GetArena());
        InternalSwap(other);
    }

    // implements Message ----------------------------------------------

    ShutdownResponse* New(::google::protobuf::Arena* arena = nullptr) const
        PROTOBUF_FINAL
    {
        return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<
            ShutdownResponse>(arena);
    }
    using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
    inline void CopyFrom(const ShutdownResponse& from)
    {
        ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
    }
    using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
    void MergeFrom(const ShutdownResponse& from)
    {
        ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
    }

   public:
    bool IsInitialized() const { return true; }

   private:
    friend class ::google::protobuf::internal::AnyMetadata;
    static ::absl::string_view FullMessageName()
    {
        return "novonotes.audio_engine.v1alpha1.ShutdownResponse";
    }

   protected:
    explicit ShutdownResponse(::google::protobuf::Arena* arena);
    ShutdownResponse(::google::protobuf::Arena* arena,
                     const ShutdownResponse& from);
    ShutdownResponse(::google::protobuf::Arena* arena,
                     ShutdownResponse&& from) noexcept
        : ShutdownResponse(arena)
    {
        *this = ::std::move(from);
    }
    const ::google::protobuf::internal::ZeroFieldsBase::ClassData*
    GetClassData() const PROTOBUF_FINAL;
    static const ::google::protobuf::internal::ZeroFieldsBase::ClassDataFull
        _class_data_;

   public:
    ::google::protobuf::Metadata GetMetadata() const;
    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------
    // @@protoc_insertion_point(class_scope:novonotes.audio_engine.v1alpha1.ShutdownResponse)
   private:
    class _Internal;
    friend class ::google::protobuf::internal::TcParser;
    static const ::google::protobuf::internal::TcParseTable<0, 0, 0, 0, 2>
        _table_;

    static constexpr const void* _raw_default_instance_ =
        &_ShutdownResponse_default_instance_;

    friend class ::google::protobuf::MessageLite;
    friend class ::google::protobuf::Arena;
    template <typename T>
    friend class ::google::protobuf::Arena::InternalHelper;
    using InternalArenaConstructable_ = void;
    using DestructorSkippable_ = void;
    struct Impl_
    {
        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(
            ::google::protobuf::internal::InternalVisibility visibility,
            ::google::protobuf::Arena* arena);
        inline explicit Impl_(
            ::google::protobuf::internal::InternalVisibility visibility,
            ::google::protobuf::Arena* arena, const Impl_& from,
            const ShutdownResponse& from_msg);
        PROTOBUF_TSAN_DECLARE_MEMBER
    };
    friend struct ::
        TableStruct_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto;
};
// -------------------------------------------------------------------

class ShutdownRequest final
    : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:novonotes.audio_engine.v1alpha1.ShutdownRequest)
 */
{
   public:
    inline ShutdownRequest() : ShutdownRequest(nullptr) {}
    template <typename = void>
    explicit PROTOBUF_CONSTEXPR ShutdownRequest(
        ::google::protobuf::internal::ConstantInitialized);

    inline ShutdownRequest(const ShutdownRequest& from)
        : ShutdownRequest(nullptr, from)
    {}
    inline ShutdownRequest(ShutdownRequest&& from) noexcept
        : ShutdownRequest(nullptr, std::move(from))
    {}
    inline ShutdownRequest& operator=(const ShutdownRequest& from)
    {
        CopyFrom(from);
        return *this;
    }
    inline ShutdownRequest& operator=(ShutdownRequest&& from) noexcept
    {
        if(this == &from) return *this;
        if(GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
           && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
        )
        {
            InternalSwap(&from);
        }
        else
        {
            CopyFrom(from);
        }
        return *this;
    }

    inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
        ABSL_ATTRIBUTE_LIFETIME_BOUND
    {
        return _internal_metadata_
            .unknown_fields<::google::protobuf::UnknownFieldSet>(
                ::google::protobuf::UnknownFieldSet::default_instance);
    }
    inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
        ABSL_ATTRIBUTE_LIFETIME_BOUND
    {
        return _internal_metadata_
            .mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
    }

    static const ::google::protobuf::Descriptor* descriptor()
    {
        return GetDescriptor();
    }
    static const ::google::protobuf::Descriptor* GetDescriptor()
    {
        return default_instance().GetMetadata().descriptor;
    }
    static const ::google::protobuf::Reflection* GetReflection()
    {
        return default_instance().GetMetadata().reflection;
    }
    static const ShutdownRequest& default_instance()
    {
        return *internal_default_instance();
    }
    static inline const ShutdownRequest* internal_default_instance()
    {
        return reinterpret_cast<const ShutdownRequest*>(
            &_ShutdownRequest_default_instance_);
    }
    static constexpr int kIndexInFileMessages = 2;
    friend void swap(ShutdownRequest& a, ShutdownRequest& b) { a.Swap(&b); }
    inline void Swap(ShutdownRequest* other)
    {
        if(other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
        if(GetArena() != nullptr && GetArena() == other->GetArena())
        {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
        if(GetArena() == other->GetArena())
        {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
            InternalSwap(other);
        }
        else
        {
            ::google::protobuf::internal::GenericSwap(this, other);
        }
    }
    void UnsafeArenaSwap(ShutdownRequest* other)
    {
        if(other == this) return;
        ABSL_DCHECK(GetArena() == other->GetArena());
        InternalSwap(other);
    }

    // implements Message ----------------------------------------------

    ShutdownRequest* New(::google::protobuf::Arena* arena = nullptr) const
        PROTOBUF_FINAL
    {
        return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<
            ShutdownRequest>(arena);
    }
    using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
    inline void CopyFrom(const ShutdownRequest& from)
    {
        ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
    }
    using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
    void MergeFrom(const ShutdownRequest& from)
    {
        ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
    }

   public:
    bool IsInitialized() const { return true; }

   private:
    friend class ::google::protobuf::internal::AnyMetadata;
    static ::absl::string_view FullMessageName()
    {
        return "novonotes.audio_engine.v1alpha1.ShutdownRequest";
    }

   protected:
    explicit ShutdownRequest(::google::protobuf::Arena* arena);
    ShutdownRequest(::google::protobuf::Arena* arena,
                    const ShutdownRequest& from);
    ShutdownRequest(::google::protobuf::Arena* arena,
                    ShutdownRequest&& from) noexcept
        : ShutdownRequest(arena)
    {
        *this = ::std::move(from);
    }
    const ::google::protobuf::internal::ZeroFieldsBase::ClassData*
    GetClassData() const PROTOBUF_FINAL;
    static const ::google::protobuf::internal::ZeroFieldsBase::ClassDataFull
        _class_data_;

   public:
    ::google::protobuf::Metadata GetMetadata() const;
    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------
    // @@protoc_insertion_point(class_scope:novonotes.audio_engine.v1alpha1.ShutdownRequest)
   private:
    class _Internal;
    friend class ::google::protobuf::internal::TcParser;
    static const ::google::protobuf::internal::TcParseTable<0, 0, 0, 0, 2>
        _table_;

    static constexpr const void* _raw_default_instance_ =
        &_ShutdownRequest_default_instance_;

    friend class ::google::protobuf::MessageLite;
    friend class ::google::protobuf::Arena;
    template <typename T>
    friend class ::google::protobuf::Arena::InternalHelper;
    using InternalArenaConstructable_ = void;
    using DestructorSkippable_ = void;
    struct Impl_
    {
        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(
            ::google::protobuf::internal::InternalVisibility visibility,
            ::google::protobuf::Arena* arena);
        inline explicit Impl_(
            ::google::protobuf::internal::InternalVisibility visibility,
            ::google::protobuf::Arena* arena, const Impl_& from,
            const ShutdownRequest& from_msg);
        PROTOBUF_TSAN_DECLARE_MEMBER
    };
    friend struct ::
        TableStruct_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto;
};
// -------------------------------------------------------------------

class ResetStateResponse final
    : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:novonotes.audio_engine.v1alpha1.ResetStateResponse)
 */
{
   public:
    inline ResetStateResponse() : ResetStateResponse(nullptr) {}
    template <typename = void>
    explicit PROTOBUF_CONSTEXPR ResetStateResponse(
        ::google::protobuf::internal::ConstantInitialized);

    inline ResetStateResponse(const ResetStateResponse& from)
        : ResetStateResponse(nullptr, from)
    {}
    inline ResetStateResponse(ResetStateResponse&& from) noexcept
        : ResetStateResponse(nullptr, std::move(from))
    {}
    inline ResetStateResponse& operator=(const ResetStateResponse& from)
    {
        CopyFrom(from);
        return *this;
    }
    inline ResetStateResponse& operator=(ResetStateResponse&& from) noexcept
    {
        if(this == &from) return *this;
        if(GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
           && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
        )
        {
            InternalSwap(&from);
        }
        else
        {
            CopyFrom(from);
        }
        return *this;
    }

    inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
        ABSL_ATTRIBUTE_LIFETIME_BOUND
    {
        return _internal_metadata_
            .unknown_fields<::google::protobuf::UnknownFieldSet>(
                ::google::protobuf::UnknownFieldSet::default_instance);
    }
    inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
        ABSL_ATTRIBUTE_LIFETIME_BOUND
    {
        return _internal_metadata_
            .mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
    }

    static const ::google::protobuf::Descriptor* descriptor()
    {
        return GetDescriptor();
    }
    static const ::google::protobuf::Descriptor* GetDescriptor()
    {
        return default_instance().GetMetadata().descriptor;
    }
    static const ::google::protobuf::Reflection* GetReflection()
    {
        return default_instance().GetMetadata().reflection;
    }
    static const ResetStateResponse& default_instance()
    {
        return *internal_default_instance();
    }
    static inline const ResetStateResponse* internal_default_instance()
    {
        return reinterpret_cast<const ResetStateResponse*>(
            &_ResetStateResponse_default_instance_);
    }
    static constexpr int kIndexInFileMessages = 5;
    friend void swap(ResetStateResponse& a, ResetStateResponse& b)
    {
        a.Swap(&b);
    }
    inline void Swap(ResetStateResponse* other)
    {
        if(other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
        if(GetArena() != nullptr && GetArena() == other->GetArena())
        {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
        if(GetArena() == other->GetArena())
        {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
            InternalSwap(other);
        }
        else
        {
            ::google::protobuf::internal::GenericSwap(this, other);
        }
    }
    void UnsafeArenaSwap(ResetStateResponse* other)
    {
        if(other == this) return;
        ABSL_DCHECK(GetArena() == other->GetArena());
        InternalSwap(other);
    }

    // implements Message ----------------------------------------------

    ResetStateResponse* New(::google::protobuf::Arena* arena = nullptr) const
        PROTOBUF_FINAL
    {
        return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<
            ResetStateResponse>(arena);
    }
    using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
    inline void CopyFrom(const ResetStateResponse& from)
    {
        ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
    }
    using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
    void MergeFrom(const ResetStateResponse& from)
    {
        ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
    }

   public:
    bool IsInitialized() const { return true; }

   private:
    friend class ::google::protobuf::internal::AnyMetadata;
    static ::absl::string_view FullMessageName()
    {
        return "novonotes.audio_engine.v1alpha1.ResetStateResponse";
    }

   protected:
    explicit ResetStateResponse(::google::protobuf::Arena* arena);
    ResetStateResponse(::google::protobuf::Arena* arena,
                       const ResetStateResponse& from);
    ResetStateResponse(::google::protobuf::Arena* arena,
                       ResetStateResponse&& from) noexcept
        : ResetStateResponse(arena)
    {
        *this = ::std::move(from);
    }
    const ::google::protobuf::internal::ZeroFieldsBase::ClassData*
    GetClassData() const PROTOBUF_FINAL;
    static const ::google::protobuf::internal::ZeroFieldsBase::ClassDataFull
        _class_data_;

   public:
    ::google::protobuf::Metadata GetMetadata() const;
    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------
    // @@protoc_insertion_point(class_scope:novonotes.audio_engine.v1alpha1.ResetStateResponse)
   private:
    class _Internal;
    friend class ::google::protobuf::internal::TcParser;
    static const ::google::protobuf::internal::TcParseTable<0, 0, 0, 0, 2>
        _table_;

    static constexpr const void* _raw_default_instance_ =
        &_ResetStateResponse_default_instance_;

    friend class ::google::protobuf::MessageLite;
    friend class ::google::protobuf::Arena;
    template <typename T>
    friend class ::google::protobuf::Arena::InternalHelper;
    using InternalArenaConstructable_ = void;
    using DestructorSkippable_ = void;
    struct Impl_
    {
        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(
            ::google::protobuf::internal::InternalVisibility visibility,
            ::google::protobuf::Arena* arena);
        inline explicit Impl_(
            ::google::protobuf::internal::InternalVisibility visibility,
            ::google::protobuf::Arena* arena, const Impl_& from,
            const ResetStateResponse& from_msg);
        PROTOBUF_TSAN_DECLARE_MEMBER
    };
    friend struct ::
        TableStruct_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto;
};
// -------------------------------------------------------------------

class ResetStateRequest final
    : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:novonotes.audio_engine.v1alpha1.ResetStateRequest)
 */
{
   public:
    inline ResetStateRequest() : ResetStateRequest(nullptr) {}
    template <typename = void>
    explicit PROTOBUF_CONSTEXPR ResetStateRequest(
        ::google::protobuf::internal::ConstantInitialized);

    inline ResetStateRequest(const ResetStateRequest& from)
        : ResetStateRequest(nullptr, from)
    {}
    inline ResetStateRequest(ResetStateRequest&& from) noexcept
        : ResetStateRequest(nullptr, std::move(from))
    {}
    inline ResetStateRequest& operator=(const ResetStateRequest& from)
    {
        CopyFrom(from);
        return *this;
    }
    inline ResetStateRequest& operator=(ResetStateRequest&& from) noexcept
    {
        if(this == &from) return *this;
        if(GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
           && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
        )
        {
            InternalSwap(&from);
        }
        else
        {
            CopyFrom(from);
        }
        return *this;
    }

    inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
        ABSL_ATTRIBUTE_LIFETIME_BOUND
    {
        return _internal_metadata_
            .unknown_fields<::google::protobuf::UnknownFieldSet>(
                ::google::protobuf::UnknownFieldSet::default_instance);
    }
    inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
        ABSL_ATTRIBUTE_LIFETIME_BOUND
    {
        return _internal_metadata_
            .mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
    }

    static const ::google::protobuf::Descriptor* descriptor()
    {
        return GetDescriptor();
    }
    static const ::google::protobuf::Descriptor* GetDescriptor()
    {
        return default_instance().GetMetadata().descriptor;
    }
    static const ::google::protobuf::Reflection* GetReflection()
    {
        return default_instance().GetMetadata().reflection;
    }
    static const ResetStateRequest& default_instance()
    {
        return *internal_default_instance();
    }
    static inline const ResetStateRequest* internal_default_instance()
    {
        return reinterpret_cast<const ResetStateRequest*>(
            &_ResetStateRequest_default_instance_);
    }
    static constexpr int kIndexInFileMessages = 4;
    friend void swap(ResetStateRequest& a, ResetStateRequest& b) { a.Swap(&b); }
    inline void Swap(ResetStateRequest* other)
    {
        if(other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
        if(GetArena() != nullptr && GetArena() == other->GetArena())
        {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
        if(GetArena() == other->GetArena())
        {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
            InternalSwap(other);
        }
        else
        {
            ::google::protobuf::internal::GenericSwap(this, other);
        }
    }
    void UnsafeArenaSwap(ResetStateRequest* other)
    {
        if(other == this) return;
        ABSL_DCHECK(GetArena() == other->GetArena());
        InternalSwap(other);
    }

    // implements Message ----------------------------------------------

    ResetStateRequest* New(::google::protobuf::Arena* arena = nullptr) const
        PROTOBUF_FINAL
    {
        return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<
            ResetStateRequest>(arena);
    }
    using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
    inline void CopyFrom(const ResetStateRequest& from)
    {
        ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
    }
    using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
    void MergeFrom(const ResetStateRequest& from)
    {
        ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
    }

   public:
    bool IsInitialized() const { return true; }

   private:
    friend class ::google::protobuf::internal::AnyMetadata;
    static ::absl::string_view FullMessageName()
    {
        return "novonotes.audio_engine.v1alpha1.ResetStateRequest";
    }

   protected:
    explicit ResetStateRequest(::google::protobuf::Arena* arena);
    ResetStateRequest(::google::protobuf::Arena* arena,
                      const ResetStateRequest& from);
    ResetStateRequest(::google::protobuf::Arena* arena,
                      ResetStateRequest&& from) noexcept
        : ResetStateRequest(arena)
    {
        *this = ::std::move(from);
    }
    const ::google::protobuf::internal::ZeroFieldsBase::ClassData*
    GetClassData() const PROTOBUF_FINAL;
    static const ::google::protobuf::internal::ZeroFieldsBase::ClassDataFull
        _class_data_;

   public:
    ::google::protobuf::Metadata GetMetadata() const;
    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------
    // @@protoc_insertion_point(class_scope:novonotes.audio_engine.v1alpha1.ResetStateRequest)
   private:
    class _Internal;
    friend class ::google::protobuf::internal::TcParser;
    static const ::google::protobuf::internal::TcParseTable<0, 0, 0, 0, 2>
        _table_;

    static constexpr const void* _raw_default_instance_ =
        &_ResetStateRequest_default_instance_;

    friend class ::google::protobuf::MessageLite;
    friend class ::google::protobuf::Arena;
    template <typename T>
    friend class ::google::protobuf::Arena::InternalHelper;
    using InternalArenaConstructable_ = void;
    using DestructorSkippable_ = void;
    struct Impl_
    {
        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(
            ::google::protobuf::internal::InternalVisibility visibility,
            ::google::protobuf::Arena* arena);
        inline explicit Impl_(
            ::google::protobuf::internal::InternalVisibility visibility,
            ::google::protobuf::Arena* arena, const Impl_& from,
            const ResetStateRequest& from_msg);
        PROTOBUF_TSAN_DECLARE_MEMBER
    };
    friend struct ::
        TableStruct_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto;
};
// -------------------------------------------------------------------

class PlayTestToneResponse final
    : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:novonotes.audio_engine.v1alpha1.PlayTestToneResponse)
 */
{
   public:
    inline PlayTestToneResponse() : PlayTestToneResponse(nullptr) {}
    template <typename = void>
    explicit PROTOBUF_CONSTEXPR PlayTestToneResponse(
        ::google::protobuf::internal::ConstantInitialized);

    inline PlayTestToneResponse(const PlayTestToneResponse& from)
        : PlayTestToneResponse(nullptr, from)
    {}
    inline PlayTestToneResponse(PlayTestToneResponse&& from) noexcept
        : PlayTestToneResponse(nullptr, std::move(from))
    {}
    inline PlayTestToneResponse& operator=(const PlayTestToneResponse& from)
    {
        CopyFrom(from);
        return *this;
    }
    inline PlayTestToneResponse& operator=(PlayTestToneResponse&& from) noexcept
    {
        if(this == &from) return *this;
        if(GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
           && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
        )
        {
            InternalSwap(&from);
        }
        else
        {
            CopyFrom(from);
        }
        return *this;
    }

    inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
        ABSL_ATTRIBUTE_LIFETIME_BOUND
    {
        return _internal_metadata_
            .unknown_fields<::google::protobuf::UnknownFieldSet>(
                ::google::protobuf::UnknownFieldSet::default_instance);
    }
    inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
        ABSL_ATTRIBUTE_LIFETIME_BOUND
    {
        return _internal_metadata_
            .mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
    }

    static const ::google::protobuf::Descriptor* descriptor()
    {
        return GetDescriptor();
    }
    static const ::google::protobuf::Descriptor* GetDescriptor()
    {
        return default_instance().GetMetadata().descriptor;
    }
    static const ::google::protobuf::Reflection* GetReflection()
    {
        return default_instance().GetMetadata().reflection;
    }
    static const PlayTestToneResponse& default_instance()
    {
        return *internal_default_instance();
    }
    static inline const PlayTestToneResponse* internal_default_instance()
    {
        return reinterpret_cast<const PlayTestToneResponse*>(
            &_PlayTestToneResponse_default_instance_);
    }
    static constexpr int kIndexInFileMessages = 7;
    friend void swap(PlayTestToneResponse& a, PlayTestToneResponse& b)
    {
        a.Swap(&b);
    }
    inline void Swap(PlayTestToneResponse* other)
    {
        if(other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
        if(GetArena() != nullptr && GetArena() == other->GetArena())
        {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
        if(GetArena() == other->GetArena())
        {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
            InternalSwap(other);
        }
        else
        {
            ::google::protobuf::internal::GenericSwap(this, other);
        }
    }
    void UnsafeArenaSwap(PlayTestToneResponse* other)
    {
        if(other == this) return;
        ABSL_DCHECK(GetArena() == other->GetArena());
        InternalSwap(other);
    }

    // implements Message ----------------------------------------------

    PlayTestToneResponse* New(::google::protobuf::Arena* arena = nullptr) const
        PROTOBUF_FINAL
    {
        return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<
            PlayTestToneResponse>(arena);
    }
    using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
    inline void CopyFrom(const PlayTestToneResponse& from)
    {
        ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
    }
    using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
    void MergeFrom(const PlayTestToneResponse& from)
    {
        ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
    }

   public:
    bool IsInitialized() const { return true; }

   private:
    friend class ::google::protobuf::internal::AnyMetadata;
    static ::absl::string_view FullMessageName()
    {
        return "novonotes.audio_engine.v1alpha1.PlayTestToneResponse";
    }

   protected:
    explicit PlayTestToneResponse(::google::protobuf::Arena* arena);
    PlayTestToneResponse(::google::protobuf::Arena* arena,
                         const PlayTestToneResponse& from);
    PlayTestToneResponse(::google::protobuf::Arena* arena,
                         PlayTestToneResponse&& from) noexcept
        : PlayTestToneResponse(arena)
    {
        *this = ::std::move(from);
    }
    const ::google::protobuf::internal::ZeroFieldsBase::ClassData*
    GetClassData() const PROTOBUF_FINAL;
    static const ::google::protobuf::internal::ZeroFieldsBase::ClassDataFull
        _class_data_;

   public:
    ::google::protobuf::Metadata GetMetadata() const;
    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------
    // @@protoc_insertion_point(class_scope:novonotes.audio_engine.v1alpha1.PlayTestToneResponse)
   private:
    class _Internal;
    friend class ::google::protobuf::internal::TcParser;
    static const ::google::protobuf::internal::TcParseTable<0, 0, 0, 0, 2>
        _table_;

    static constexpr const void* _raw_default_instance_ =
        &_PlayTestToneResponse_default_instance_;

    friend class ::google::protobuf::MessageLite;
    friend class ::google::protobuf::Arena;
    template <typename T>
    friend class ::google::protobuf::Arena::InternalHelper;
    using InternalArenaConstructable_ = void;
    using DestructorSkippable_ = void;
    struct Impl_
    {
        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(
            ::google::protobuf::internal::InternalVisibility visibility,
            ::google::protobuf::Arena* arena);
        inline explicit Impl_(
            ::google::protobuf::internal::InternalVisibility visibility,
            ::google::protobuf::Arena* arena, const Impl_& from,
            const PlayTestToneResponse& from_msg);
        PROTOBUF_TSAN_DECLARE_MEMBER
    };
    friend struct ::
        TableStruct_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto;
};
// -------------------------------------------------------------------

class PlayTestToneRequest final
    : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:novonotes.audio_engine.v1alpha1.PlayTestToneRequest)
 */
{
   public:
    inline PlayTestToneRequest() : PlayTestToneRequest(nullptr) {}
    template <typename = void>
    explicit PROTOBUF_CONSTEXPR PlayTestToneRequest(
        ::google::protobuf::internal::ConstantInitialized);

    inline PlayTestToneRequest(const PlayTestToneRequest& from)
        : PlayTestToneRequest(nullptr, from)
    {}
    inline PlayTestToneRequest(PlayTestToneRequest&& from) noexcept
        : PlayTestToneRequest(nullptr, std::move(from))
    {}
    inline PlayTestToneRequest& operator=(const PlayTestToneRequest& from)
    {
        CopyFrom(from);
        return *this;
    }
    inline PlayTestToneRequest& operator=(PlayTestToneRequest&& from) noexcept
    {
        if(this == &from) return *this;
        if(GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
           && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
        )
        {
            InternalSwap(&from);
        }
        else
        {
            CopyFrom(from);
        }
        return *this;
    }

    inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
        ABSL_ATTRIBUTE_LIFETIME_BOUND
    {
        return _internal_metadata_
            .unknown_fields<::google::protobuf::UnknownFieldSet>(
                ::google::protobuf::UnknownFieldSet::default_instance);
    }
    inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
        ABSL_ATTRIBUTE_LIFETIME_BOUND
    {
        return _internal_metadata_
            .mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
    }

    static const ::google::protobuf::Descriptor* descriptor()
    {
        return GetDescriptor();
    }
    static const ::google::protobuf::Descriptor* GetDescriptor()
    {
        return default_instance().GetMetadata().descriptor;
    }
    static const ::google::protobuf::Reflection* GetReflection()
    {
        return default_instance().GetMetadata().reflection;
    }
    static const PlayTestToneRequest& default_instance()
    {
        return *internal_default_instance();
    }
    static inline const PlayTestToneRequest* internal_default_instance()
    {
        return reinterpret_cast<const PlayTestToneRequest*>(
            &_PlayTestToneRequest_default_instance_);
    }
    static constexpr int kIndexInFileMessages = 6;
    friend void swap(PlayTestToneRequest& a, PlayTestToneRequest& b)
    {
        a.Swap(&b);
    }
    inline void Swap(PlayTestToneRequest* other)
    {
        if(other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
        if(GetArena() != nullptr && GetArena() == other->GetArena())
        {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
        if(GetArena() == other->GetArena())
        {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
            InternalSwap(other);
        }
        else
        {
            ::google::protobuf::internal::GenericSwap(this, other);
        }
    }
    void UnsafeArenaSwap(PlayTestToneRequest* other)
    {
        if(other == this) return;
        ABSL_DCHECK(GetArena() == other->GetArena());
        InternalSwap(other);
    }

    // implements Message ----------------------------------------------

    PlayTestToneRequest* New(::google::protobuf::Arena* arena = nullptr) const
        PROTOBUF_FINAL
    {
        return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<
            PlayTestToneRequest>(arena);
    }
    using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
    inline void CopyFrom(const PlayTestToneRequest& from)
    {
        ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
    }
    using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
    void MergeFrom(const PlayTestToneRequest& from)
    {
        ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
    }

   public:
    bool IsInitialized() const { return true; }

   private:
    friend class ::google::protobuf::internal::AnyMetadata;
    static ::absl::string_view FullMessageName()
    {
        return "novonotes.audio_engine.v1alpha1.PlayTestToneRequest";
    }

   protected:
    explicit PlayTestToneRequest(::google::protobuf::Arena* arena);
    PlayTestToneRequest(::google::protobuf::Arena* arena,
                        const PlayTestToneRequest& from);
    PlayTestToneRequest(::google::protobuf::Arena* arena,
                        PlayTestToneRequest&& from) noexcept
        : PlayTestToneRequest(arena)
    {
        *this = ::std::move(from);
    }
    const ::google::protobuf::internal::ZeroFieldsBase::ClassData*
    GetClassData() const PROTOBUF_FINAL;
    static const ::google::protobuf::internal::ZeroFieldsBase::ClassDataFull
        _class_data_;

   public:
    ::google::protobuf::Metadata GetMetadata() const;
    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------
    // @@protoc_insertion_point(class_scope:novonotes.audio_engine.v1alpha1.PlayTestToneRequest)
   private:
    class _Internal;
    friend class ::google::protobuf::internal::TcParser;
    static const ::google::protobuf::internal::TcParseTable<0, 0, 0, 0, 2>
        _table_;

    static constexpr const void* _raw_default_instance_ =
        &_PlayTestToneRequest_default_instance_;

    friend class ::google::protobuf::MessageLite;
    friend class ::google::protobuf::Arena;
    template <typename T>
    friend class ::google::protobuf::Arena::InternalHelper;
    using InternalArenaConstructable_ = void;
    using DestructorSkippable_ = void;
    struct Impl_
    {
        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(
            ::google::protobuf::internal::InternalVisibility visibility,
            ::google::protobuf::Arena* arena);
        inline explicit Impl_(
            ::google::protobuf::internal::InternalVisibility visibility,
            ::google::protobuf::Arena* arena, const Impl_& from,
            const PlayTestToneRequest& from_msg);
        PROTOBUF_TSAN_DECLARE_MEMBER
    };
    friend struct ::
        TableStruct_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto;
};
// -------------------------------------------------------------------

class InitializeResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:novonotes.audio_engine.v1alpha1.InitializeResponse)
 */
{
   public:
    inline InitializeResponse() : InitializeResponse(nullptr) {}
    ~InitializeResponse() PROTOBUF_FINAL;
    template <typename = void>
    explicit PROTOBUF_CONSTEXPR InitializeResponse(
        ::google::protobuf::internal::ConstantInitialized);

    inline InitializeResponse(const InitializeResponse& from)
        : InitializeResponse(nullptr, from)
    {}
    inline InitializeResponse(InitializeResponse&& from) noexcept
        : InitializeResponse(nullptr, std::move(from))
    {}
    inline InitializeResponse& operator=(const InitializeResponse& from)
    {
        CopyFrom(from);
        return *this;
    }
    inline InitializeResponse& operator=(InitializeResponse&& from) noexcept
    {
        if(this == &from) return *this;
        if(GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
           && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
        )
        {
            InternalSwap(&from);
        }
        else
        {
            CopyFrom(from);
        }
        return *this;
    }

    inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
        ABSL_ATTRIBUTE_LIFETIME_BOUND
    {
        return _internal_metadata_
            .unknown_fields<::google::protobuf::UnknownFieldSet>(
                ::google::protobuf::UnknownFieldSet::default_instance);
    }
    inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
        ABSL_ATTRIBUTE_LIFETIME_BOUND
    {
        return _internal_metadata_
            .mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
    }

    static const ::google::protobuf::Descriptor* descriptor()
    {
        return GetDescriptor();
    }
    static const ::google::protobuf::Descriptor* GetDescriptor()
    {
        return default_instance().GetMetadata().descriptor;
    }
    static const ::google::protobuf::Reflection* GetReflection()
    {
        return default_instance().GetMetadata().reflection;
    }
    static const InitializeResponse& default_instance()
    {
        return *internal_default_instance();
    }
    static inline const InitializeResponse* internal_default_instance()
    {
        return reinterpret_cast<const InitializeResponse*>(
            &_InitializeResponse_default_instance_);
    }
    static constexpr int kIndexInFileMessages = 1;
    friend void swap(InitializeResponse& a, InitializeResponse& b)
    {
        a.Swap(&b);
    }
    inline void Swap(InitializeResponse* other)
    {
        if(other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
        if(GetArena() != nullptr && GetArena() == other->GetArena())
        {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
        if(GetArena() == other->GetArena())
        {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
            InternalSwap(other);
        }
        else
        {
            ::google::protobuf::internal::GenericSwap(this, other);
        }
    }
    void UnsafeArenaSwap(InitializeResponse* other)
    {
        if(other == this) return;
        ABSL_DCHECK(GetArena() == other->GetArena());
        InternalSwap(other);
    }

    // implements Message ----------------------------------------------

    InitializeResponse* New(::google::protobuf::Arena* arena = nullptr) const
        PROTOBUF_FINAL
    {
        return ::google::protobuf::Message::DefaultConstruct<
            InitializeResponse>(arena);
    }
    using ::google::protobuf::Message::CopyFrom;
    void CopyFrom(const InitializeResponse& from);
    using ::google::protobuf::Message::MergeFrom;
    void MergeFrom(const InitializeResponse& from)
    {
        InitializeResponse::MergeImpl(*this, from);
    }

   private:
    static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                          const ::google::protobuf::MessageLite& from_msg);

   public:
    bool IsInitialized() const { return true; }
    ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
#if defined(PROTOBUF_CUSTOM_VTABLE)
   private:
    static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
    static ::uint8_t* _InternalSerialize(
        const MessageLite& msg, ::uint8_t* target,
        ::google::protobuf::io::EpsCopyOutputStream* stream);

   public:
    ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
    ::uint8_t* _InternalSerialize(
        ::uint8_t* target,
        ::google::protobuf::io::EpsCopyOutputStream* stream) const
    {
        return _InternalSerialize(*this, target, stream);
    }
#else   // PROTOBUF_CUSTOM_VTABLE
    ::size_t ByteSizeLong() const final;
    ::uint8_t* _InternalSerialize(
        ::uint8_t* target,
        ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
#endif  // PROTOBUF_CUSTOM_VTABLE
    int GetCachedSize() const { return _impl_._cached_size_.Get(); }

   private:
    void SharedCtor(::google::protobuf::Arena* arena);
    void SharedDtor();
    void InternalSwap(InitializeResponse* other);

   private:
    friend class ::google::protobuf::internal::AnyMetadata;
    static ::absl::string_view FullMessageName()
    {
        return "novonotes.audio_engine.v1alpha1.InitializeResponse";
    }

   protected:
    explicit InitializeResponse(::google::protobuf::Arena* arena);
    InitializeResponse(::google::protobuf::Arena* arena,
                       const InitializeResponse& from);
    InitializeResponse(::google::protobuf::Arena* arena,
                       InitializeResponse&& from) noexcept
        : InitializeResponse(arena)
    {
        *this = ::std::move(from);
    }
    const ::google::protobuf::Message::ClassData* GetClassData() const
        PROTOBUF_FINAL;
    static const ::google::protobuf::Message::ClassDataFull _class_data_;

   public:
    ::google::protobuf::Metadata GetMetadata() const;
    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------
    enum : int
    {
        kEngineTypeIdFieldNumber = 3,
        kDisplayNameFieldNumber = 4,
        kSchemaVersionFieldNumber = 6,
        kPidFieldNumber = 7,
    };
    // string engine_type_id = 3;
    void clear_engine_type_id();
    const std::string& engine_type_id() const;
    template <typename Arg_ = const std::string&, typename... Args_>
    void set_engine_type_id(Arg_&& arg, Args_... args);
    std::string* mutable_engine_type_id();
    PROTOBUF_NODISCARD std::string* release_engine_type_id();
    void set_allocated_engine_type_id(std::string* value);

   private:
    const std::string& _internal_engine_type_id() const;
    inline PROTOBUF_ALWAYS_INLINE void _internal_set_engine_type_id(
        const std::string& value);
    std::string* _internal_mutable_engine_type_id();

   public:
    // string display_name = 4;
    void clear_display_name();
    const std::string& display_name() const;
    template <typename Arg_ = const std::string&, typename... Args_>
    void set_display_name(Arg_&& arg, Args_... args);
    std::string* mutable_display_name();
    PROTOBUF_NODISCARD std::string* release_display_name();
    void set_allocated_display_name(std::string* value);

   private:
    const std::string& _internal_display_name() const;
    inline PROTOBUF_ALWAYS_INLINE void _internal_set_display_name(
        const std::string& value);
    std::string* _internal_mutable_display_name();

   public:
    // string schema_version = 6;
    void clear_schema_version();
    const std::string& schema_version() const;
    template <typename Arg_ = const std::string&, typename... Args_>
    void set_schema_version(Arg_&& arg, Args_... args);
    std::string* mutable_schema_version();
    PROTOBUF_NODISCARD std::string* release_schema_version();
    void set_allocated_schema_version(std::string* value);

   private:
    const std::string& _internal_schema_version() const;
    inline PROTOBUF_ALWAYS_INLINE void _internal_set_schema_version(
        const std::string& value);
    std::string* _internal_mutable_schema_version();

   public:
    // int32 pid = 7;
    void clear_pid();
    ::int32_t pid() const;
    void set_pid(::int32_t value);

   private:
    ::int32_t _internal_pid() const;
    void _internal_set_pid(::int32_t value);

   public:
    // @@protoc_insertion_point(class_scope:novonotes.audio_engine.v1alpha1.InitializeResponse)
   private:
    class _Internal;
    friend class ::google::protobuf::internal::TcParser;
    static const ::google::protobuf::internal::TcParseTable<3, 4, 0, 99, 2>
        _table_;

    static constexpr const void* _raw_default_instance_ =
        &_InitializeResponse_default_instance_;

    friend class ::google::protobuf::MessageLite;
    friend class ::google::protobuf::Arena;
    template <typename T>
    friend class ::google::protobuf::Arena::InternalHelper;
    using InternalArenaConstructable_ = void;
    using DestructorSkippable_ = void;
    struct Impl_
    {
        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(
            ::google::protobuf::internal::InternalVisibility visibility,
            ::google::protobuf::Arena* arena);
        inline explicit Impl_(
            ::google::protobuf::internal::InternalVisibility visibility,
            ::google::protobuf::Arena* arena, const Impl_& from,
            const InitializeResponse& from_msg);
        ::google::protobuf::internal::ArenaStringPtr engine_type_id_;
        ::google::protobuf::internal::ArenaStringPtr display_name_;
        ::google::protobuf::internal::ArenaStringPtr schema_version_;
        ::int32_t pid_;
        mutable ::google::protobuf::internal::CachedSize _cached_size_;
        PROTOBUF_TSAN_DECLARE_MEMBER
    };
    union
    {
        Impl_ _impl_;
    };
    friend struct ::
        TableStruct_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto;
};
// -------------------------------------------------------------------

class InitializeRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:novonotes.audio_engine.v1alpha1.InitializeRequest)
 */
{
   public:
    inline InitializeRequest() : InitializeRequest(nullptr) {}
    ~InitializeRequest() PROTOBUF_FINAL;
    template <typename = void>
    explicit PROTOBUF_CONSTEXPR InitializeRequest(
        ::google::protobuf::internal::ConstantInitialized);

    inline InitializeRequest(const InitializeRequest& from)
        : InitializeRequest(nullptr, from)
    {}
    inline InitializeRequest(InitializeRequest&& from) noexcept
        : InitializeRequest(nullptr, std::move(from))
    {}
    inline InitializeRequest& operator=(const InitializeRequest& from)
    {
        CopyFrom(from);
        return *this;
    }
    inline InitializeRequest& operator=(InitializeRequest&& from) noexcept
    {
        if(this == &from) return *this;
        if(GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
           && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
        )
        {
            InternalSwap(&from);
        }
        else
        {
            CopyFrom(from);
        }
        return *this;
    }

    inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
        ABSL_ATTRIBUTE_LIFETIME_BOUND
    {
        return _internal_metadata_
            .unknown_fields<::google::protobuf::UnknownFieldSet>(
                ::google::protobuf::UnknownFieldSet::default_instance);
    }
    inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
        ABSL_ATTRIBUTE_LIFETIME_BOUND
    {
        return _internal_metadata_
            .mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
    }

    static const ::google::protobuf::Descriptor* descriptor()
    {
        return GetDescriptor();
    }
    static const ::google::protobuf::Descriptor* GetDescriptor()
    {
        return default_instance().GetMetadata().descriptor;
    }
    static const ::google::protobuf::Reflection* GetReflection()
    {
        return default_instance().GetMetadata().reflection;
    }
    static const InitializeRequest& default_instance()
    {
        return *internal_default_instance();
    }
    static inline const InitializeRequest* internal_default_instance()
    {
        return reinterpret_cast<const InitializeRequest*>(
            &_InitializeRequest_default_instance_);
    }
    static constexpr int kIndexInFileMessages = 0;
    friend void swap(InitializeRequest& a, InitializeRequest& b) { a.Swap(&b); }
    inline void Swap(InitializeRequest* other)
    {
        if(other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
        if(GetArena() != nullptr && GetArena() == other->GetArena())
        {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
        if(GetArena() == other->GetArena())
        {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
            InternalSwap(other);
        }
        else
        {
            ::google::protobuf::internal::GenericSwap(this, other);
        }
    }
    void UnsafeArenaSwap(InitializeRequest* other)
    {
        if(other == this) return;
        ABSL_DCHECK(GetArena() == other->GetArena());
        InternalSwap(other);
    }

    // implements Message ----------------------------------------------

    InitializeRequest* New(::google::protobuf::Arena* arena = nullptr) const
        PROTOBUF_FINAL
    {
        return ::google::protobuf::Message::DefaultConstruct<InitializeRequest>(
            arena);
    }
    using ::google::protobuf::Message::CopyFrom;
    void CopyFrom(const InitializeRequest& from);
    using ::google::protobuf::Message::MergeFrom;
    void MergeFrom(const InitializeRequest& from)
    {
        InitializeRequest::MergeImpl(*this, from);
    }

   private:
    static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                          const ::google::protobuf::MessageLite& from_msg);

   public:
    bool IsInitialized() const { return true; }
    ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
#if defined(PROTOBUF_CUSTOM_VTABLE)
   private:
    static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
    static ::uint8_t* _InternalSerialize(
        const MessageLite& msg, ::uint8_t* target,
        ::google::protobuf::io::EpsCopyOutputStream* stream);

   public:
    ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
    ::uint8_t* _InternalSerialize(
        ::uint8_t* target,
        ::google::protobuf::io::EpsCopyOutputStream* stream) const
    {
        return _InternalSerialize(*this, target, stream);
    }
#else   // PROTOBUF_CUSTOM_VTABLE
    ::size_t ByteSizeLong() const final;
    ::uint8_t* _InternalSerialize(
        ::uint8_t* target,
        ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
#endif  // PROTOBUF_CUSTOM_VTABLE
    int GetCachedSize() const { return _impl_._cached_size_.Get(); }

   private:
    void SharedCtor(::google::protobuf::Arena* arena);
    void SharedDtor();
    void InternalSwap(InitializeRequest* other);

   private:
    friend class ::google::protobuf::internal::AnyMetadata;
    static ::absl::string_view FullMessageName()
    {
        return "novonotes.audio_engine.v1alpha1.InitializeRequest";
    }

   protected:
    explicit InitializeRequest(::google::protobuf::Arena* arena);
    InitializeRequest(::google::protobuf::Arena* arena,
                      const InitializeRequest& from);
    InitializeRequest(::google::protobuf::Arena* arena,
                      InitializeRequest&& from) noexcept
        : InitializeRequest(arena)
    {
        *this = ::std::move(from);
    }
    const ::google::protobuf::Message::ClassData* GetClassData() const
        PROTOBUF_FINAL;
    static const ::google::protobuf::Message::ClassDataFull _class_data_;

   public:
    ::google::protobuf::Metadata GetMetadata() const;
    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------
    enum : int
    {
        kAppInstanceIdFieldNumber = 1,
        kSchemaVersionFieldNumber = 2,
    };
    // string app_instance_id = 1;
    void clear_app_instance_id();
    const std::string& app_instance_id() const;
    template <typename Arg_ = const std::string&, typename... Args_>
    void set_app_instance_id(Arg_&& arg, Args_... args);
    std::string* mutable_app_instance_id();
    PROTOBUF_NODISCARD std::string* release_app_instance_id();
    void set_allocated_app_instance_id(std::string* value);

   private:
    const std::string& _internal_app_instance_id() const;
    inline PROTOBUF_ALWAYS_INLINE void _internal_set_app_instance_id(
        const std::string& value);
    std::string* _internal_mutable_app_instance_id();

   public:
    // string schema_version = 2;
    void clear_schema_version();
    const std::string& schema_version() const;
    template <typename Arg_ = const std::string&, typename... Args_>
    void set_schema_version(Arg_&& arg, Args_... args);
    std::string* mutable_schema_version();
    PROTOBUF_NODISCARD std::string* release_schema_version();
    void set_allocated_schema_version(std::string* value);

   private:
    const std::string& _internal_schema_version() const;
    inline PROTOBUF_ALWAYS_INLINE void _internal_set_schema_version(
        const std::string& value);
    std::string* _internal_mutable_schema_version();

   public:
    // @@protoc_insertion_point(class_scope:novonotes.audio_engine.v1alpha1.InitializeRequest)
   private:
    class _Internal;
    friend class ::google::protobuf::internal::TcParser;
    static const ::google::protobuf::internal::TcParseTable<1, 2, 0, 87, 2>
        _table_;

    static constexpr const void* _raw_default_instance_ =
        &_InitializeRequest_default_instance_;

    friend class ::google::protobuf::MessageLite;
    friend class ::google::protobuf::Arena;
    template <typename T>
    friend class ::google::protobuf::Arena::InternalHelper;
    using InternalArenaConstructable_ = void;
    using DestructorSkippable_ = void;
    struct Impl_
    {
        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(
            ::google::protobuf::internal::InternalVisibility visibility,
            ::google::protobuf::Arena* arena);
        inline explicit Impl_(
            ::google::protobuf::internal::InternalVisibility visibility,
            ::google::protobuf::Arena* arena, const Impl_& from,
            const InitializeRequest& from_msg);
        ::google::protobuf::internal::ArenaStringPtr app_instance_id_;
        ::google::protobuf::internal::ArenaStringPtr schema_version_;
        mutable ::google::protobuf::internal::CachedSize _cached_size_;
        PROTOBUF_TSAN_DECLARE_MEMBER
    };
    union
    {
        Impl_ _impl_;
    };
    friend struct ::
        TableStruct_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto;
};

// ===================================================================

// ===================================================================

#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// InitializeRequest

// string app_instance_id = 1;
inline void InitializeRequest::clear_app_instance_id()
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.app_instance_id_.ClearToEmpty();
}
inline const std::string& InitializeRequest::app_instance_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND
{
    // @@protoc_insertion_point(field_get:novonotes.audio_engine.v1alpha1.InitializeRequest.app_instance_id)
    return _internal_app_instance_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void InitializeRequest::set_app_instance_id(
    Arg_&& arg, Args_... args)
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.app_instance_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
    // @@protoc_insertion_point(field_set:novonotes.audio_engine.v1alpha1.InitializeRequest.app_instance_id)
}
inline std::string* InitializeRequest::mutable_app_instance_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND
{
    std::string* _s = _internal_mutable_app_instance_id();
    // @@protoc_insertion_point(field_mutable:novonotes.audio_engine.v1alpha1.InitializeRequest.app_instance_id)
    return _s;
}
inline const std::string& InitializeRequest::_internal_app_instance_id() const
{
    ::google::protobuf::internal::TSanRead(&_impl_);
    return _impl_.app_instance_id_.Get();
}
inline void InitializeRequest::_internal_set_app_instance_id(
    const std::string& value)
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.app_instance_id_.Set(value, GetArena());
}
inline std::string* InitializeRequest::_internal_mutable_app_instance_id()
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    return _impl_.app_instance_id_.Mutable(GetArena());
}
inline std::string* InitializeRequest::release_app_instance_id()
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    // @@protoc_insertion_point(field_release:novonotes.audio_engine.v1alpha1.InitializeRequest.app_instance_id)
    return _impl_.app_instance_id_.Release();
}
inline void InitializeRequest::set_allocated_app_instance_id(std::string* value)
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.app_instance_id_.SetAllocated(value, GetArena());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    if(_impl_.app_instance_id_.IsDefault())
    {
        _impl_.app_instance_id_.Set("", GetArena());
    }
#endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
    // @@protoc_insertion_point(field_set_allocated:novonotes.audio_engine.v1alpha1.InitializeRequest.app_instance_id)
}

// string schema_version = 2;
inline void InitializeRequest::clear_schema_version()
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.schema_version_.ClearToEmpty();
}
inline const std::string& InitializeRequest::schema_version() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND
{
    // @@protoc_insertion_point(field_get:novonotes.audio_engine.v1alpha1.InitializeRequest.schema_version)
    return _internal_schema_version();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void InitializeRequest::set_schema_version(
    Arg_&& arg, Args_... args)
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.schema_version_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
    // @@protoc_insertion_point(field_set:novonotes.audio_engine.v1alpha1.InitializeRequest.schema_version)
}
inline std::string* InitializeRequest::mutable_schema_version()
    ABSL_ATTRIBUTE_LIFETIME_BOUND
{
    std::string* _s = _internal_mutable_schema_version();
    // @@protoc_insertion_point(field_mutable:novonotes.audio_engine.v1alpha1.InitializeRequest.schema_version)
    return _s;
}
inline const std::string& InitializeRequest::_internal_schema_version() const
{
    ::google::protobuf::internal::TSanRead(&_impl_);
    return _impl_.schema_version_.Get();
}
inline void InitializeRequest::_internal_set_schema_version(
    const std::string& value)
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.schema_version_.Set(value, GetArena());
}
inline std::string* InitializeRequest::_internal_mutable_schema_version()
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    return _impl_.schema_version_.Mutable(GetArena());
}
inline std::string* InitializeRequest::release_schema_version()
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    // @@protoc_insertion_point(field_release:novonotes.audio_engine.v1alpha1.InitializeRequest.schema_version)
    return _impl_.schema_version_.Release();
}
inline void InitializeRequest::set_allocated_schema_version(std::string* value)
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.schema_version_.SetAllocated(value, GetArena());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    if(_impl_.schema_version_.IsDefault())
    {
        _impl_.schema_version_.Set("", GetArena());
    }
#endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
    // @@protoc_insertion_point(field_set_allocated:novonotes.audio_engine.v1alpha1.InitializeRequest.schema_version)
}

// -------------------------------------------------------------------

// InitializeResponse

// string engine_type_id = 3;
inline void InitializeResponse::clear_engine_type_id()
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.engine_type_id_.ClearToEmpty();
}
inline const std::string& InitializeResponse::engine_type_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND
{
    // @@protoc_insertion_point(field_get:novonotes.audio_engine.v1alpha1.InitializeResponse.engine_type_id)
    return _internal_engine_type_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void InitializeResponse::set_engine_type_id(
    Arg_&& arg, Args_... args)
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.engine_type_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
    // @@protoc_insertion_point(field_set:novonotes.audio_engine.v1alpha1.InitializeResponse.engine_type_id)
}
inline std::string* InitializeResponse::mutable_engine_type_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND
{
    std::string* _s = _internal_mutable_engine_type_id();
    // @@protoc_insertion_point(field_mutable:novonotes.audio_engine.v1alpha1.InitializeResponse.engine_type_id)
    return _s;
}
inline const std::string& InitializeResponse::_internal_engine_type_id() const
{
    ::google::protobuf::internal::TSanRead(&_impl_);
    return _impl_.engine_type_id_.Get();
}
inline void InitializeResponse::_internal_set_engine_type_id(
    const std::string& value)
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.engine_type_id_.Set(value, GetArena());
}
inline std::string* InitializeResponse::_internal_mutable_engine_type_id()
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    return _impl_.engine_type_id_.Mutable(GetArena());
}
inline std::string* InitializeResponse::release_engine_type_id()
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    // @@protoc_insertion_point(field_release:novonotes.audio_engine.v1alpha1.InitializeResponse.engine_type_id)
    return _impl_.engine_type_id_.Release();
}
inline void InitializeResponse::set_allocated_engine_type_id(std::string* value)
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.engine_type_id_.SetAllocated(value, GetArena());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    if(_impl_.engine_type_id_.IsDefault())
    {
        _impl_.engine_type_id_.Set("", GetArena());
    }
#endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
    // @@protoc_insertion_point(field_set_allocated:novonotes.audio_engine.v1alpha1.InitializeResponse.engine_type_id)
}

// string display_name = 4;
inline void InitializeResponse::clear_display_name()
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.display_name_.ClearToEmpty();
}
inline const std::string& InitializeResponse::display_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND
{
    // @@protoc_insertion_point(field_get:novonotes.audio_engine.v1alpha1.InitializeResponse.display_name)
    return _internal_display_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void InitializeResponse::set_display_name(
    Arg_&& arg, Args_... args)
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.display_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
    // @@protoc_insertion_point(field_set:novonotes.audio_engine.v1alpha1.InitializeResponse.display_name)
}
inline std::string* InitializeResponse::mutable_display_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND
{
    std::string* _s = _internal_mutable_display_name();
    // @@protoc_insertion_point(field_mutable:novonotes.audio_engine.v1alpha1.InitializeResponse.display_name)
    return _s;
}
inline const std::string& InitializeResponse::_internal_display_name() const
{
    ::google::protobuf::internal::TSanRead(&_impl_);
    return _impl_.display_name_.Get();
}
inline void InitializeResponse::_internal_set_display_name(
    const std::string& value)
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.display_name_.Set(value, GetArena());
}
inline std::string* InitializeResponse::_internal_mutable_display_name()
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    return _impl_.display_name_.Mutable(GetArena());
}
inline std::string* InitializeResponse::release_display_name()
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    // @@protoc_insertion_point(field_release:novonotes.audio_engine.v1alpha1.InitializeResponse.display_name)
    return _impl_.display_name_.Release();
}
inline void InitializeResponse::set_allocated_display_name(std::string* value)
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.display_name_.SetAllocated(value, GetArena());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    if(_impl_.display_name_.IsDefault())
    {
        _impl_.display_name_.Set("", GetArena());
    }
#endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
    // @@protoc_insertion_point(field_set_allocated:novonotes.audio_engine.v1alpha1.InitializeResponse.display_name)
}

// string schema_version = 6;
inline void InitializeResponse::clear_schema_version()
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.schema_version_.ClearToEmpty();
}
inline const std::string& InitializeResponse::schema_version() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND
{
    // @@protoc_insertion_point(field_get:novonotes.audio_engine.v1alpha1.InitializeResponse.schema_version)
    return _internal_schema_version();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void InitializeResponse::set_schema_version(
    Arg_&& arg, Args_... args)
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.schema_version_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
    // @@protoc_insertion_point(field_set:novonotes.audio_engine.v1alpha1.InitializeResponse.schema_version)
}
inline std::string* InitializeResponse::mutable_schema_version()
    ABSL_ATTRIBUTE_LIFETIME_BOUND
{
    std::string* _s = _internal_mutable_schema_version();
    // @@protoc_insertion_point(field_mutable:novonotes.audio_engine.v1alpha1.InitializeResponse.schema_version)
    return _s;
}
inline const std::string& InitializeResponse::_internal_schema_version() const
{
    ::google::protobuf::internal::TSanRead(&_impl_);
    return _impl_.schema_version_.Get();
}
inline void InitializeResponse::_internal_set_schema_version(
    const std::string& value)
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.schema_version_.Set(value, GetArena());
}
inline std::string* InitializeResponse::_internal_mutable_schema_version()
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    return _impl_.schema_version_.Mutable(GetArena());
}
inline std::string* InitializeResponse::release_schema_version()
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    // @@protoc_insertion_point(field_release:novonotes.audio_engine.v1alpha1.InitializeResponse.schema_version)
    return _impl_.schema_version_.Release();
}
inline void InitializeResponse::set_allocated_schema_version(std::string* value)
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.schema_version_.SetAllocated(value, GetArena());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    if(_impl_.schema_version_.IsDefault())
    {
        _impl_.schema_version_.Set("", GetArena());
    }
#endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
    // @@protoc_insertion_point(field_set_allocated:novonotes.audio_engine.v1alpha1.InitializeResponse.schema_version)
}

// int32 pid = 7;
inline void InitializeResponse::clear_pid()
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.pid_ = 0;
}
inline ::int32_t InitializeResponse::pid() const
{
    // @@protoc_insertion_point(field_get:novonotes.audio_engine.v1alpha1.InitializeResponse.pid)
    return _internal_pid();
}
inline void InitializeResponse::set_pid(::int32_t value)
{
    _internal_set_pid(value);
    // @@protoc_insertion_point(field_set:novonotes.audio_engine.v1alpha1.InitializeResponse.pid)
}
inline ::int32_t InitializeResponse::_internal_pid() const
{
    ::google::protobuf::internal::TSanRead(&_impl_);
    return _impl_.pid_;
}
inline void InitializeResponse::_internal_set_pid(::int32_t value)
{
    ::google::protobuf::internal::TSanWrite(&_impl_);
    _impl_.pid_ = value;
}

// -------------------------------------------------------------------

// ShutdownRequest

// -------------------------------------------------------------------

// ShutdownResponse

// -------------------------------------------------------------------

// ResetStateRequest

// -------------------------------------------------------------------

// ResetStateResponse

// -------------------------------------------------------------------

// PlayTestToneRequest

// -------------------------------------------------------------------

// PlayTestToneResponse

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1alpha1
}  // namespace audio_engine
}  // namespace novonotes

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto_2epb_2eh
