// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: novonotes/audio_engine/v1alpha1/engine_management.proto
// Protobuf C++ Version: 5.28.1

#include "novonotes/audio_engine/v1alpha1/engine_management.pb.h"

#include <algorithm>
#include <type_traits>

#include "google/protobuf/descriptor.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/wire_format_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace novonotes
{
namespace audio_engine
{
namespace v1alpha1
{
template <typename>
PROTOBUF_CONSTEXPR ShutdownResponse::ShutdownResponse(
    ::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase()
{
}
#endif  // PROTOBUF_CUSTOM_VTABLE
    struct ShutdownResponseDefaultTypeInternal
{
    PROTOBUF_CONSTEXPR ShutdownResponseDefaultTypeInternal()
        : _instance(::_pbi::ConstantInitialized{})
    {}
    ~ShutdownResponseDefaultTypeInternal() {}
    union
    {
        ShutdownResponse _instance;
    };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ShutdownResponseDefaultTypeInternal
        _ShutdownResponse_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR ShutdownRequest::ShutdownRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase()
{
}
#endif  // PROTOBUF_CUSTOM_VTABLE
    struct ShutdownRequestDefaultTypeInternal
{
    PROTOBUF_CONSTEXPR ShutdownRequestDefaultTypeInternal()
        : _instance(::_pbi::ConstantInitialized{})
    {}
    ~ShutdownRequestDefaultTypeInternal() {}
    union
    {
        ShutdownRequest _instance;
    };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ShutdownRequestDefaultTypeInternal
        _ShutdownRequest_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR ResetStateResponse::ResetStateResponse(
    ::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase()
{
}
#endif  // PROTOBUF_CUSTOM_VTABLE
    struct ResetStateResponseDefaultTypeInternal
{
    PROTOBUF_CONSTEXPR ResetStateResponseDefaultTypeInternal()
        : _instance(::_pbi::ConstantInitialized{})
    {}
    ~ResetStateResponseDefaultTypeInternal() {}
    union
    {
        ResetStateResponse _instance;
    };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResetStateResponseDefaultTypeInternal
        _ResetStateResponse_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR ResetStateRequest::ResetStateRequest(
    ::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase()
{
}
#endif  // PROTOBUF_CUSTOM_VTABLE
    struct ResetStateRequestDefaultTypeInternal
{
    PROTOBUF_CONSTEXPR ResetStateRequestDefaultTypeInternal()
        : _instance(::_pbi::ConstantInitialized{})
    {}
    ~ResetStateRequestDefaultTypeInternal() {}
    union
    {
        ResetStateRequest _instance;
    };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResetStateRequestDefaultTypeInternal
        _ResetStateRequest_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR PlayTestToneResponse::PlayTestToneResponse(
    ::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase()
{
}
#endif  // PROTOBUF_CUSTOM_VTABLE
    struct PlayTestToneResponseDefaultTypeInternal
{
    PROTOBUF_CONSTEXPR PlayTestToneResponseDefaultTypeInternal()
        : _instance(::_pbi::ConstantInitialized{})
    {}
    ~PlayTestToneResponseDefaultTypeInternal() {}
    union
    {
        PlayTestToneResponse _instance;
    };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayTestToneResponseDefaultTypeInternal
        _PlayTestToneResponse_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR PlayTestToneRequest::PlayTestToneRequest(
    ::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase()
{
}
#endif  // PROTOBUF_CUSTOM_VTABLE
    struct PlayTestToneRequestDefaultTypeInternal
{
    PROTOBUF_CONSTEXPR PlayTestToneRequestDefaultTypeInternal()
        : _instance(::_pbi::ConstantInitialized{})
    {}
    ~PlayTestToneRequestDefaultTypeInternal() {}
    union
    {
        PlayTestToneRequest _instance;
    };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayTestToneRequestDefaultTypeInternal
        _PlayTestToneRequest_default_instance_;

inline constexpr InitializeResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
    : engine_type_id_(&::google::protobuf::internal::fixed_address_empty_string,
                      ::_pbi::ConstantInitialized())
    , display_name_(&::google::protobuf::internal::fixed_address_empty_string,
                    ::_pbi::ConstantInitialized())
    , schema_version_(&::google::protobuf::internal::fixed_address_empty_string,
                      ::_pbi::ConstantInitialized())
    , pid_{0}
    , _cached_size_{0}
{}

template <typename>
PROTOBUF_CONSTEXPR InitializeResponse::InitializeResponse(
    ::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base())
    ,
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message()
    ,
#endif  // PROTOBUF_CUSTOM_VTABLE
    _impl_(::_pbi::ConstantInitialized())
{}
struct InitializeResponseDefaultTypeInternal
{
    PROTOBUF_CONSTEXPR InitializeResponseDefaultTypeInternal()
        : _instance(::_pbi::ConstantInitialized{})
    {}
    ~InitializeResponseDefaultTypeInternal() {}
    union
    {
        InitializeResponse _instance;
    };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InitializeResponseDefaultTypeInternal
        _InitializeResponse_default_instance_;

inline constexpr InitializeRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
    : app_instance_id_(
          &::google::protobuf::internal::fixed_address_empty_string,
          ::_pbi::ConstantInitialized())
    , schema_version_(&::google::protobuf::internal::fixed_address_empty_string,
                      ::_pbi::ConstantInitialized())
    , _cached_size_{0}
{}

template <typename>
PROTOBUF_CONSTEXPR InitializeRequest::InitializeRequest(
    ::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base())
    ,
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message()
    ,
#endif  // PROTOBUF_CUSTOM_VTABLE
    _impl_(::_pbi::ConstantInitialized())
{}
struct InitializeRequestDefaultTypeInternal
{
    PROTOBUF_CONSTEXPR InitializeRequestDefaultTypeInternal()
        : _instance(::_pbi::ConstantInitialized{})
    {}
    ~InitializeRequestDefaultTypeInternal() {}
    union
    {
        InitializeRequest _instance;
    };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InitializeRequestDefaultTypeInternal
        _InitializeRequest_default_instance_;
}  // namespace v1alpha1
}  // namespace audio_engine
}  // namespace novonotes
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto =
        nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto =
        nullptr;
const ::uint32_t
    TableStruct_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto::
        offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
            ~0u,  // no _has_bits_
            PROTOBUF_FIELD_OFFSET(
                ::novonotes::audio_engine::v1alpha1::InitializeRequest,
                _internal_metadata_),
            ~0u,  // no _extensions_
            ~0u,  // no _oneof_case_
            ~0u,  // no _weak_field_map_
            ~0u,  // no _inlined_string_donated_
            ~0u,  // no _split_
            ~0u,  // no sizeof(Split)
            PROTOBUF_FIELD_OFFSET(
                ::novonotes::audio_engine::v1alpha1::InitializeRequest,
                _impl_.app_instance_id_),
            PROTOBUF_FIELD_OFFSET(
                ::novonotes::audio_engine::v1alpha1::InitializeRequest,
                _impl_.schema_version_),
            ~0u,  // no _has_bits_
            PROTOBUF_FIELD_OFFSET(
                ::novonotes::audio_engine::v1alpha1::InitializeResponse,
                _internal_metadata_),
            ~0u,  // no _extensions_
            ~0u,  // no _oneof_case_
            ~0u,  // no _weak_field_map_
            ~0u,  // no _inlined_string_donated_
            ~0u,  // no _split_
            ~0u,  // no sizeof(Split)
            PROTOBUF_FIELD_OFFSET(
                ::novonotes::audio_engine::v1alpha1::InitializeResponse,
                _impl_.engine_type_id_),
            PROTOBUF_FIELD_OFFSET(
                ::novonotes::audio_engine::v1alpha1::InitializeResponse,
                _impl_.display_name_),
            PROTOBUF_FIELD_OFFSET(
                ::novonotes::audio_engine::v1alpha1::InitializeResponse,
                _impl_.schema_version_),
            PROTOBUF_FIELD_OFFSET(
                ::novonotes::audio_engine::v1alpha1::InitializeResponse,
                _impl_.pid_),
            ~0u,  // no _has_bits_
            PROTOBUF_FIELD_OFFSET(
                ::novonotes::audio_engine::v1alpha1::ShutdownRequest,
                _internal_metadata_),
            ~0u,  // no _extensions_
            ~0u,  // no _oneof_case_
            ~0u,  // no _weak_field_map_
            ~0u,  // no _inlined_string_donated_
            ~0u,  // no _split_
            ~0u,  // no sizeof(Split)
            ~0u,  // no _has_bits_
            PROTOBUF_FIELD_OFFSET(
                ::novonotes::audio_engine::v1alpha1::ShutdownResponse,
                _internal_metadata_),
            ~0u,  // no _extensions_
            ~0u,  // no _oneof_case_
            ~0u,  // no _weak_field_map_
            ~0u,  // no _inlined_string_donated_
            ~0u,  // no _split_
            ~0u,  // no sizeof(Split)
            ~0u,  // no _has_bits_
            PROTOBUF_FIELD_OFFSET(
                ::novonotes::audio_engine::v1alpha1::ResetStateRequest,
                _internal_metadata_),
            ~0u,  // no _extensions_
            ~0u,  // no _oneof_case_
            ~0u,  // no _weak_field_map_
            ~0u,  // no _inlined_string_donated_
            ~0u,  // no _split_
            ~0u,  // no sizeof(Split)
            ~0u,  // no _has_bits_
            PROTOBUF_FIELD_OFFSET(
                ::novonotes::audio_engine::v1alpha1::ResetStateResponse,
                _internal_metadata_),
            ~0u,  // no _extensions_
            ~0u,  // no _oneof_case_
            ~0u,  // no _weak_field_map_
            ~0u,  // no _inlined_string_donated_
            ~0u,  // no _split_
            ~0u,  // no sizeof(Split)
            ~0u,  // no _has_bits_
            PROTOBUF_FIELD_OFFSET(
                ::novonotes::audio_engine::v1alpha1::PlayTestToneRequest,
                _internal_metadata_),
            ~0u,  // no _extensions_
            ~0u,  // no _oneof_case_
            ~0u,  // no _weak_field_map_
            ~0u,  // no _inlined_string_donated_
            ~0u,  // no _split_
            ~0u,  // no sizeof(Split)
            ~0u,  // no _has_bits_
            PROTOBUF_FIELD_OFFSET(
                ::novonotes::audio_engine::v1alpha1::PlayTestToneResponse,
                _internal_metadata_),
            ~0u,  // no _extensions_
            ~0u,  // no _oneof_case_
            ~0u,  // no _weak_field_map_
            ~0u,  // no _inlined_string_donated_
            ~0u,  // no _split_
            ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    {0, -1, -1, sizeof(::novonotes::audio_engine::v1alpha1::InitializeRequest)},
    {10, -1, -1,
     sizeof(::novonotes::audio_engine::v1alpha1::InitializeResponse)},
    {22, -1, -1, sizeof(::novonotes::audio_engine::v1alpha1::ShutdownRequest)},
    {30, -1, -1, sizeof(::novonotes::audio_engine::v1alpha1::ShutdownResponse)},
    {38, -1, -1,
     sizeof(::novonotes::audio_engine::v1alpha1::ResetStateRequest)},
    {46, -1, -1,
     sizeof(::novonotes::audio_engine::v1alpha1::ResetStateResponse)},
    {54, -1, -1,
     sizeof(::novonotes::audio_engine::v1alpha1::PlayTestToneRequest)},
    {62, -1, -1,
     sizeof(::novonotes::audio_engine::v1alpha1::PlayTestToneResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::novonotes::audio_engine::v1alpha1::_InitializeRequest_default_instance_
         ._instance,
    &::novonotes::audio_engine::v1alpha1::_InitializeResponse_default_instance_
         ._instance,
    &::novonotes::audio_engine::v1alpha1::_ShutdownRequest_default_instance_
         ._instance,
    &::novonotes::audio_engine::v1alpha1::_ShutdownResponse_default_instance_
         ._instance,
    &::novonotes::audio_engine::v1alpha1::_ResetStateRequest_default_instance_
         ._instance,
    &::novonotes::audio_engine::v1alpha1::_ResetStateResponse_default_instance_
         ._instance,
    &::novonotes::audio_engine::v1alpha1::_PlayTestToneRequest_default_instance_
         ._instance,
    &::novonotes::audio_engine::v1alpha1::
         _PlayTestToneResponse_default_instance_._instance,
};
const char
    descriptor_table_protodef_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto
        [] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
            "\n7novonotes/audio_engine/v1alpha1/engine"
            "_management.proto\022\037novonotes.audio_engin"
            "e.v1alpha1\"D\n\021InitializeRequest\022\027\n\017app_i"
            "nstance_id\030\001 \001(\t\022\026\n\016schema_version\030\002 "
            "\001(\t"
            "\"g\n\022InitializeResponse\022\026\n\016engine_type_id"
            "\030\003 \001(\t\022\024\n\014display_name\030\004 "
            "\001(\t\022\026\n\016schema_v"
            "ersion\030\006 \001(\t\022\013\n\003pid\030\007 "
            "\001(\005\"\021\n\017ShutdownReq"
            "uest\"\022\n\020ShutdownResponse\"\023\n\021ResetStateRe"
            "quest\"\024\n\022ResetStateResponse\"\025\n\023PlayTestT"
            "oneRequest\"\026\n\024PlayTestToneResponseb\006prot"
            "o3"};
static ::absl::once_flag
    descriptor_table_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable
    descriptor_table_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto = {
        false,
        false,
        402,
        descriptor_table_protodef_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto,
        "novonotes/audio_engine/v1alpha1/engine_management.proto",
        &descriptor_table_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto_once,
        nullptr,
        0,
        8,
        schemas,
        file_default_instances,
        TableStruct_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto::
            offsets,
        file_level_enum_descriptors_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto,
        file_level_service_descriptors_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto,
};
namespace novonotes
{
namespace audio_engine
{
namespace v1alpha1
{
// ===================================================================

class InitializeRequest::_Internal
{
   public:
};

InitializeRequest::InitializeRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
    SharedCtor(arena);
    // @@protoc_insertion_point(arena_constructor:novonotes.audio_engine.v1alpha1.InitializeRequest)
}
inline PROTOBUF_NDEBUG_INLINE InitializeRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena, const Impl_& from,
    const ::novonotes::audio_engine::v1alpha1::InitializeRequest& from_msg)
    : app_instance_id_(arena, from.app_instance_id_)
    , schema_version_(arena, from.schema_version_)
    , _cached_size_{0}
{}

InitializeRequest::InitializeRequest(::google::protobuf::Arena* arena,
                                     const InitializeRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
    InitializeRequest* const _this = this;
    (void)_this;
    _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
        from._internal_metadata_);
    new(&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

    // @@protoc_insertion_point(copy_constructor:novonotes.audio_engine.v1alpha1.InitializeRequest)
}
inline PROTOBUF_NDEBUG_INLINE InitializeRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
    : app_instance_id_(arena)
    , schema_version_(arena)
    , _cached_size_{0}
{}

inline void InitializeRequest::SharedCtor(::_pb::Arena* arena)
{
    new(&_impl_) Impl_(internal_visibility(), arena);
}
InitializeRequest::~InitializeRequest()
{
    // @@protoc_insertion_point(destructor:novonotes.audio_engine.v1alpha1.InitializeRequest)
    _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
    SharedDtor();
}
inline void InitializeRequest::SharedDtor()
{
    ABSL_DCHECK(GetArena() == nullptr);
    _impl_.app_instance_id_.Destroy();
    _impl_.schema_version_.Destroy();
    _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    InitializeRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_InitializeRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &InitializeRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<InitializeRequest>(),
            ::google::protobuf::Message::GetNewImpl<InitializeRequest>(),
            ::google::protobuf::Message::GetClearImpl<InitializeRequest>(),
            &InitializeRequest::ByteSizeLong,
            &InitializeRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(InitializeRequest, _impl_._cached_size_),
            false,
        },
        &InitializeRequest::kDescriptorMethods,
        &descriptor_table_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto,
        nullptr,  // tracker
    };
const ::google::protobuf::MessageLite::ClassData*
InitializeRequest::GetClassData() const
{
    ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
    ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
    return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<
    1, 2, 0, 87, 2>
    InitializeRequest::_table_ = {
        {
            0,     // no _has_bits_
            0,     // no _extensions_
            2, 8,  // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967292,  // skipmap
            offsetof(decltype(_table_), field_entries),
            2,                                         // num_field_entries
            0,                                         // num_aux_entries
            offsetof(decltype(_table_), field_names),  // no aux_entries
            _class_data_.base(),
            nullptr,                            // post_loop_handler
            ::_pbi::TcParser::GenericFallback,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<::novonotes::audio_engine::v1alpha1::
                                           InitializeRequest>(),  // to_prefetch
#endif  // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            // string schema_version = 2;
            {::_pbi::TcParser::FastUS1,
             {18, 63, 0,
              PROTOBUF_FIELD_OFFSET(InitializeRequest,
                                    _impl_.schema_version_)}},
            // string app_instance_id = 1;
            {::_pbi::TcParser::FastUS1,
             {10, 63, 0,
              PROTOBUF_FIELD_OFFSET(InitializeRequest,
                                    _impl_.app_instance_id_)}},
        }},
        {{65535, 65535}},
        {{
            // string app_instance_id = 1;
            {PROTOBUF_FIELD_OFFSET(InitializeRequest, _impl_.app_instance_id_),
             0, 0,
             (0 | ::_fl::kFcSingular | ::_fl::kUtf8String |
              ::_fl::kRepAString)},
            // string schema_version = 2;
            {PROTOBUF_FIELD_OFFSET(InitializeRequest, _impl_.schema_version_),
             0, 0,
             (0 | ::_fl::kFcSingular | ::_fl::kUtf8String |
              ::_fl::kRepAString)},
        }},
        // no aux_entries
        {{"\61\17\16\0\0\0\0\0"
          "novonotes.audio_engine.v1alpha1.InitializeRequest"
          "app_instance_id"
          "schema_version"}},
    };

PROTOBUF_NOINLINE void InitializeRequest::Clear()
{
    // @@protoc_insertion_point(message_clear_start:novonotes.audio_engine.v1alpha1.InitializeRequest)
    ::google::protobuf::internal::TSanWrite(&_impl_);
    ::uint32_t cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    _impl_.app_instance_id_.ClearToEmpty();
    _impl_.schema_version_.ClearToEmpty();
    _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* InitializeRequest::_InternalSerialize(
    const MessageLite& base, ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream)
{
    const InitializeRequest& this_ =
        static_cast<const InitializeRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* InitializeRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const
{
    const InitializeRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
        // @@protoc_insertion_point(serialize_to_array_start:novonotes.audio_engine.v1alpha1.InitializeRequest)
    ::uint32_t cached_has_bits = 0;
    (void)cached_has_bits;

    // string app_instance_id = 1;
    if(!this_._internal_app_instance_id().empty())
    {
        const std::string& _s = this_._internal_app_instance_id();
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            _s.data(), static_cast<int>(_s.length()),
            ::google::protobuf::internal::WireFormatLite::SERIALIZE,
            "novonotes.audio_engine.v1alpha1.InitializeRequest.app_instance_"
            "id");
        target = stream->WriteStringMaybeAliased(1, _s, target);
    }

    // string schema_version = 2;
    if(!this_._internal_schema_version().empty())
    {
        const std::string& _s = this_._internal_schema_version();
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            _s.data(), static_cast<int>(_s.length()),
            ::google::protobuf::internal::WireFormatLite::SERIALIZE,
            "novonotes.audio_engine.v1alpha1.InitializeRequest.schema_version");
        target = stream->WriteStringMaybeAliased(2, _s, target);
    }

    if(PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields()))
    {
        target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_
                .unknown_fields<::google::protobuf::UnknownFieldSet>(
                    ::google::protobuf::UnknownFieldSet::default_instance),
            target, stream);
    }
    // @@protoc_insertion_point(serialize_to_array_end:novonotes.audio_engine.v1alpha1.InitializeRequest)
    return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t InitializeRequest::ByteSizeLong(const MessageLite& base)
{
    const InitializeRequest& this_ =
        static_cast<const InitializeRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t InitializeRequest::ByteSizeLong() const
{
    const InitializeRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
        // @@protoc_insertion_point(message_byte_size_start:novonotes.audio_engine.v1alpha1.InitializeRequest)
    ::size_t total_size = 0;

    ::uint32_t cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    ::_pbi::Prefetch5LinesFrom7Lines(&this_);
    {
        // string app_instance_id = 1;
        if(!this_._internal_app_instance_id().empty())
        {
            total_size +=
                1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                        this_._internal_app_instance_id());
        }
        // string schema_version = 2;
        if(!this_._internal_schema_version().empty())
        {
            total_size +=
                1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                        this_._internal_schema_version());
        }
    }
    return this_.MaybeComputeUnknownFieldsSize(total_size,
                                               &this_._impl_._cached_size_);
}

void InitializeRequest::MergeImpl(
    ::google::protobuf::MessageLite& to_msg,
    const ::google::protobuf::MessageLite& from_msg)
{
    auto* const _this = static_cast<InitializeRequest*>(&to_msg);
    auto& from = static_cast<const InitializeRequest&>(from_msg);
    // @@protoc_insertion_point(class_specific_merge_from_start:novonotes.audio_engine.v1alpha1.InitializeRequest)
    ABSL_DCHECK_NE(&from, _this);
    ::uint32_t cached_has_bits = 0;
    (void)cached_has_bits;

    if(!from._internal_app_instance_id().empty())
    {
        _this->_internal_set_app_instance_id(from._internal_app_instance_id());
    }
    if(!from._internal_schema_version().empty())
    {
        _this->_internal_set_schema_version(from._internal_schema_version());
    }
    _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
        from._internal_metadata_);
}

void InitializeRequest::CopyFrom(const InitializeRequest& from)
{
    // @@protoc_insertion_point(class_specific_copy_from_start:novonotes.audio_engine.v1alpha1.InitializeRequest)
    if(&from == this) return;
    Clear();
    MergeFrom(from);
}

void InitializeRequest::InternalSwap(InitializeRequest* PROTOBUF_RESTRICT other)
{
    using std::swap;
    auto* arena = GetArena();
    ABSL_DCHECK_EQ(arena, other->GetArena());
    _internal_metadata_.InternalSwap(&other->_internal_metadata_);
    ::_pbi::ArenaStringPtr::InternalSwap(
        &_impl_.app_instance_id_, &other->_impl_.app_instance_id_, arena);
    ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.schema_version_,
                                         &other->_impl_.schema_version_, arena);
}

::google::protobuf::Metadata InitializeRequest::GetMetadata() const
{
    return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class InitializeResponse::_Internal
{
   public:
};

InitializeResponse::InitializeResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
    SharedCtor(arena);
    // @@protoc_insertion_point(arena_constructor:novonotes.audio_engine.v1alpha1.InitializeResponse)
}
inline PROTOBUF_NDEBUG_INLINE InitializeResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena, const Impl_& from,
    const ::novonotes::audio_engine::v1alpha1::InitializeResponse& from_msg)
    : engine_type_id_(arena, from.engine_type_id_)
    , display_name_(arena, from.display_name_)
    , schema_version_(arena, from.schema_version_)
    , _cached_size_{0}
{}

InitializeResponse::InitializeResponse(::google::protobuf::Arena* arena,
                                       const InitializeResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
    InitializeResponse* const _this = this;
    (void)_this;
    _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
        from._internal_metadata_);
    new(&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
    _impl_.pid_ = from._impl_.pid_;

    // @@protoc_insertion_point(copy_constructor:novonotes.audio_engine.v1alpha1.InitializeResponse)
}
inline PROTOBUF_NDEBUG_INLINE InitializeResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
    : engine_type_id_(arena)
    , display_name_(arena)
    , schema_version_(arena)
    , _cached_size_{0}
{}

inline void InitializeResponse::SharedCtor(::_pb::Arena* arena)
{
    new(&_impl_) Impl_(internal_visibility(), arena);
    _impl_.pid_ = {};
}
InitializeResponse::~InitializeResponse()
{
    // @@protoc_insertion_point(destructor:novonotes.audio_engine.v1alpha1.InitializeResponse)
    _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
    SharedDtor();
}
inline void InitializeResponse::SharedDtor()
{
    ABSL_DCHECK(GetArena() == nullptr);
    _impl_.engine_type_id_.Destroy();
    _impl_.display_name_.Destroy();
    _impl_.schema_version_.Destroy();
    _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    InitializeResponse::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_InitializeResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &InitializeResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<InitializeResponse>(),
            ::google::protobuf::Message::GetNewImpl<InitializeResponse>(),
            ::google::protobuf::Message::GetClearImpl<InitializeResponse>(),
            &InitializeResponse::ByteSizeLong,
            &InitializeResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(InitializeResponse, _impl_._cached_size_),
            false,
        },
        &InitializeResponse::kDescriptorMethods,
        &descriptor_table_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto,
        nullptr,  // tracker
    };
const ::google::protobuf::MessageLite::ClassData*
InitializeResponse::GetClassData() const
{
    ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
    ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
    return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<
    3, 4, 0, 99, 2>
    InitializeResponse::_table_ = {
        {
            0,      // no _has_bits_
            0,      // no _extensions_
            7, 56,  // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967187,  // skipmap
            offsetof(decltype(_table_), field_entries),
            4,                                         // num_field_entries
            0,                                         // num_aux_entries
            offsetof(decltype(_table_), field_names),  // no aux_entries
            _class_data_.base(),
            nullptr,                            // post_loop_handler
            ::_pbi::TcParser::GenericFallback,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<
                ::novonotes::audio_engine::v1alpha1::
                    InitializeResponse>(),  // to_prefetch
#endif                                      // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            {::_pbi::TcParser::MiniParse, {}},
            {::_pbi::TcParser::MiniParse, {}},
            {::_pbi::TcParser::MiniParse, {}},
            // string engine_type_id = 3;
            {::_pbi::TcParser::FastUS1,
             {26, 63, 0,
              PROTOBUF_FIELD_OFFSET(InitializeResponse,
                                    _impl_.engine_type_id_)}},
            // string display_name = 4;
            {::_pbi::TcParser::FastUS1,
             {34, 63, 0,
              PROTOBUF_FIELD_OFFSET(InitializeResponse, _impl_.display_name_)}},
            {::_pbi::TcParser::MiniParse, {}},
            // string schema_version = 6;
            {::_pbi::TcParser::FastUS1,
             {50, 63, 0,
              PROTOBUF_FIELD_OFFSET(InitializeResponse,
                                    _impl_.schema_version_)}},
            // int32 pid = 7;
            {::_pbi::TcParser::SingularVarintNoZag1<
                 ::uint32_t, offsetof(InitializeResponse, _impl_.pid_), 63>(),
             {56, 63, 0,
              PROTOBUF_FIELD_OFFSET(InitializeResponse, _impl_.pid_)}},
        }},
        {{65535, 65535}},
        {{
            // string engine_type_id = 3;
            {PROTOBUF_FIELD_OFFSET(InitializeResponse, _impl_.engine_type_id_),
             0, 0,
             (0 | ::_fl::kFcSingular | ::_fl::kUtf8String |
              ::_fl::kRepAString)},
            // string display_name = 4;
            {PROTOBUF_FIELD_OFFSET(InitializeResponse, _impl_.display_name_), 0,
             0,
             (0 | ::_fl::kFcSingular | ::_fl::kUtf8String |
              ::_fl::kRepAString)},
            // string schema_version = 6;
            {PROTOBUF_FIELD_OFFSET(InitializeResponse, _impl_.schema_version_),
             0, 0,
             (0 | ::_fl::kFcSingular | ::_fl::kUtf8String |
              ::_fl::kRepAString)},
            // int32 pid = 7;
            {PROTOBUF_FIELD_OFFSET(InitializeResponse, _impl_.pid_), 0, 0,
             (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
        }},
        // no aux_entries
        {{"\62\16\14\16\0\0\0\0"
          "novonotes.audio_engine.v1alpha1.InitializeResponse"
          "engine_type_id"
          "display_name"
          "schema_version"}},
    };

PROTOBUF_NOINLINE void InitializeResponse::Clear()
{
    // @@protoc_insertion_point(message_clear_start:novonotes.audio_engine.v1alpha1.InitializeResponse)
    ::google::protobuf::internal::TSanWrite(&_impl_);
    ::uint32_t cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    _impl_.engine_type_id_.ClearToEmpty();
    _impl_.display_name_.ClearToEmpty();
    _impl_.schema_version_.ClearToEmpty();
    _impl_.pid_ = 0;
    _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* InitializeResponse::_InternalSerialize(
    const MessageLite& base, ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream)
{
    const InitializeResponse& this_ =
        static_cast<const InitializeResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* InitializeResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const
{
    const InitializeResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
        // @@protoc_insertion_point(serialize_to_array_start:novonotes.audio_engine.v1alpha1.InitializeResponse)
    ::uint32_t cached_has_bits = 0;
    (void)cached_has_bits;

    // string engine_type_id = 3;
    if(!this_._internal_engine_type_id().empty())
    {
        const std::string& _s = this_._internal_engine_type_id();
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            _s.data(), static_cast<int>(_s.length()),
            ::google::protobuf::internal::WireFormatLite::SERIALIZE,
            "novonotes.audio_engine.v1alpha1.InitializeResponse.engine_type_"
            "id");
        target = stream->WriteStringMaybeAliased(3, _s, target);
    }

    // string display_name = 4;
    if(!this_._internal_display_name().empty())
    {
        const std::string& _s = this_._internal_display_name();
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            _s.data(), static_cast<int>(_s.length()),
            ::google::protobuf::internal::WireFormatLite::SERIALIZE,
            "novonotes.audio_engine.v1alpha1.InitializeResponse.display_name");
        target = stream->WriteStringMaybeAliased(4, _s, target);
    }

    // string schema_version = 6;
    if(!this_._internal_schema_version().empty())
    {
        const std::string& _s = this_._internal_schema_version();
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            _s.data(), static_cast<int>(_s.length()),
            ::google::protobuf::internal::WireFormatLite::SERIALIZE,
            "novonotes.audio_engine.v1alpha1.InitializeResponse.schema_"
            "version");
        target = stream->WriteStringMaybeAliased(6, _s, target);
    }

    // int32 pid = 7;
    if(this_._internal_pid() != 0)
    {
        target = ::google::protobuf::internal::WireFormatLite::
            WriteInt32ToArrayWithField<7>(stream, this_._internal_pid(),
                                          target);
    }

    if(PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields()))
    {
        target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_
                .unknown_fields<::google::protobuf::UnknownFieldSet>(
                    ::google::protobuf::UnknownFieldSet::default_instance),
            target, stream);
    }
    // @@protoc_insertion_point(serialize_to_array_end:novonotes.audio_engine.v1alpha1.InitializeResponse)
    return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t InitializeResponse::ByteSizeLong(const MessageLite& base)
{
    const InitializeResponse& this_ =
        static_cast<const InitializeResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t InitializeResponse::ByteSizeLong() const
{
    const InitializeResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
        // @@protoc_insertion_point(message_byte_size_start:novonotes.audio_engine.v1alpha1.InitializeResponse)
    ::size_t total_size = 0;

    ::uint32_t cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    ::_pbi::Prefetch5LinesFrom7Lines(&this_);
    {
        // string engine_type_id = 3;
        if(!this_._internal_engine_type_id().empty())
        {
            total_size +=
                1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                        this_._internal_engine_type_id());
        }
        // string display_name = 4;
        if(!this_._internal_display_name().empty())
        {
            total_size +=
                1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                        this_._internal_display_name());
        }
        // string schema_version = 6;
        if(!this_._internal_schema_version().empty())
        {
            total_size +=
                1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                        this_._internal_schema_version());
        }
        // int32 pid = 7;
        if(this_._internal_pid() != 0)
        {
            total_size +=
                ::_pbi::WireFormatLite::Int32SizePlusOne(this_._internal_pid());
        }
    }
    return this_.MaybeComputeUnknownFieldsSize(total_size,
                                               &this_._impl_._cached_size_);
}

void InitializeResponse::MergeImpl(
    ::google::protobuf::MessageLite& to_msg,
    const ::google::protobuf::MessageLite& from_msg)
{
    auto* const _this = static_cast<InitializeResponse*>(&to_msg);
    auto& from = static_cast<const InitializeResponse&>(from_msg);
    // @@protoc_insertion_point(class_specific_merge_from_start:novonotes.audio_engine.v1alpha1.InitializeResponse)
    ABSL_DCHECK_NE(&from, _this);
    ::uint32_t cached_has_bits = 0;
    (void)cached_has_bits;

    if(!from._internal_engine_type_id().empty())
    {
        _this->_internal_set_engine_type_id(from._internal_engine_type_id());
    }
    if(!from._internal_display_name().empty())
    {
        _this->_internal_set_display_name(from._internal_display_name());
    }
    if(!from._internal_schema_version().empty())
    {
        _this->_internal_set_schema_version(from._internal_schema_version());
    }
    if(from._internal_pid() != 0)
    {
        _this->_impl_.pid_ = from._impl_.pid_;
    }
    _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
        from._internal_metadata_);
}

void InitializeResponse::CopyFrom(const InitializeResponse& from)
{
    // @@protoc_insertion_point(class_specific_copy_from_start:novonotes.audio_engine.v1alpha1.InitializeResponse)
    if(&from == this) return;
    Clear();
    MergeFrom(from);
}

void InitializeResponse::InternalSwap(
    InitializeResponse* PROTOBUF_RESTRICT other)
{
    using std::swap;
    auto* arena = GetArena();
    ABSL_DCHECK_EQ(arena, other->GetArena());
    _internal_metadata_.InternalSwap(&other->_internal_metadata_);
    ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.engine_type_id_,
                                         &other->_impl_.engine_type_id_, arena);
    ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.display_name_,
                                         &other->_impl_.display_name_, arena);
    ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.schema_version_,
                                         &other->_impl_.schema_version_, arena);
    swap(_impl_.pid_, other->_impl_.pid_);
}

::google::protobuf::Metadata InitializeResponse::GetMetadata() const
{
    return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ShutdownRequest::_Internal
{
   public:
};

ShutdownRequest::ShutdownRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
    // @@protoc_insertion_point(arena_constructor:novonotes.audio_engine.v1alpha1.ShutdownRequest)
}
ShutdownRequest::ShutdownRequest(::google::protobuf::Arena* arena,
                                 const ShutdownRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
    ShutdownRequest* const _this = this;
    (void)_this;
    _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
        from._internal_metadata_);

    // @@protoc_insertion_point(copy_constructor:novonotes.audio_engine.v1alpha1.ShutdownRequest)
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ShutdownRequest::_class_data_ = {
        ::google::protobuf::internal::ZeroFieldsBase::ClassData{
            &_ShutdownRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ShutdownRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::internal::ZeroFieldsBase::GetDeleteImpl<
                ShutdownRequest>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<
                ShutdownRequest>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<
                ShutdownRequest>(),
            &ShutdownRequest::ByteSizeLong,
            &ShutdownRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ShutdownRequest, _impl_._cached_size_),
            false,
        },
        &ShutdownRequest::kDescriptorMethods,
        &descriptor_table_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto,
        nullptr,  // tracker
    };
const ::google::protobuf::MessageLite::ClassData*
ShutdownRequest::GetClassData() const
{
    ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
    ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
    return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<
    0, 0, 0, 0, 2>
    ShutdownRequest::_table_ = {
        {
            0,     // no _has_bits_
            0,     // no _extensions_
            0, 0,  // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967295,                                // skipmap
            offsetof(decltype(_table_), field_names),  // no field_entries
            0,                                         // num_field_entries
            0,                                         // num_aux_entries
            offsetof(decltype(_table_), field_names),  // no aux_entries
            _class_data_.base(),
            nullptr,                            // post_loop_handler
            ::_pbi::TcParser::GenericFallback,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<::novonotes::audio_engine::v1alpha1::
                                           ShutdownRequest>(),  // to_prefetch
#endif  // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            {::_pbi::TcParser::MiniParse, {}},
        }},
        {{65535, 65535}},
        // no field_entries, or aux_entries
        {{}},
    };

::google::protobuf::Metadata ShutdownRequest::GetMetadata() const
{
    return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(
        GetClassData()->full());
}
// ===================================================================

class ShutdownResponse::_Internal
{
   public:
};

ShutdownResponse::ShutdownResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
    // @@protoc_insertion_point(arena_constructor:novonotes.audio_engine.v1alpha1.ShutdownResponse)
}
ShutdownResponse::ShutdownResponse(::google::protobuf::Arena* arena,
                                   const ShutdownResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
    ShutdownResponse* const _this = this;
    (void)_this;
    _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
        from._internal_metadata_);

    // @@protoc_insertion_point(copy_constructor:novonotes.audio_engine.v1alpha1.ShutdownResponse)
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ShutdownResponse::_class_data_ = {
        ::google::protobuf::internal::ZeroFieldsBase::ClassData{
            &_ShutdownResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ShutdownResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::internal::ZeroFieldsBase::GetDeleteImpl<
                ShutdownResponse>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<
                ShutdownResponse>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<
                ShutdownResponse>(),
            &ShutdownResponse::ByteSizeLong,
            &ShutdownResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ShutdownResponse, _impl_._cached_size_),
            false,
        },
        &ShutdownResponse::kDescriptorMethods,
        &descriptor_table_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto,
        nullptr,  // tracker
    };
const ::google::protobuf::MessageLite::ClassData*
ShutdownResponse::GetClassData() const
{
    ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
    ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
    return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<
    0, 0, 0, 0, 2>
    ShutdownResponse::_table_ = {
        {
            0,     // no _has_bits_
            0,     // no _extensions_
            0, 0,  // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967295,                                // skipmap
            offsetof(decltype(_table_), field_names),  // no field_entries
            0,                                         // num_field_entries
            0,                                         // num_aux_entries
            offsetof(decltype(_table_), field_names),  // no aux_entries
            _class_data_.base(),
            nullptr,                            // post_loop_handler
            ::_pbi::TcParser::GenericFallback,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<::novonotes::audio_engine::v1alpha1::
                                           ShutdownResponse>(),  // to_prefetch
#endif  // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            {::_pbi::TcParser::MiniParse, {}},
        }},
        {{65535, 65535}},
        // no field_entries, or aux_entries
        {{}},
    };

::google::protobuf::Metadata ShutdownResponse::GetMetadata() const
{
    return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(
        GetClassData()->full());
}
// ===================================================================

class ResetStateRequest::_Internal
{
   public:
};

ResetStateRequest::ResetStateRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
    // @@protoc_insertion_point(arena_constructor:novonotes.audio_engine.v1alpha1.ResetStateRequest)
}
ResetStateRequest::ResetStateRequest(::google::protobuf::Arena* arena,
                                     const ResetStateRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
    ResetStateRequest* const _this = this;
    (void)_this;
    _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
        from._internal_metadata_);

    // @@protoc_insertion_point(copy_constructor:novonotes.audio_engine.v1alpha1.ResetStateRequest)
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ResetStateRequest::_class_data_ = {
        ::google::protobuf::internal::ZeroFieldsBase::ClassData{
            &_ResetStateRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ResetStateRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::internal::ZeroFieldsBase::GetDeleteImpl<
                ResetStateRequest>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<
                ResetStateRequest>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<
                ResetStateRequest>(),
            &ResetStateRequest::ByteSizeLong,
            &ResetStateRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ResetStateRequest, _impl_._cached_size_),
            false,
        },
        &ResetStateRequest::kDescriptorMethods,
        &descriptor_table_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto,
        nullptr,  // tracker
    };
const ::google::protobuf::MessageLite::ClassData*
ResetStateRequest::GetClassData() const
{
    ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
    ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
    return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<
    0, 0, 0, 0, 2>
    ResetStateRequest::_table_ = {
        {
            0,     // no _has_bits_
            0,     // no _extensions_
            0, 0,  // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967295,                                // skipmap
            offsetof(decltype(_table_), field_names),  // no field_entries
            0,                                         // num_field_entries
            0,                                         // num_aux_entries
            offsetof(decltype(_table_), field_names),  // no aux_entries
            _class_data_.base(),
            nullptr,                            // post_loop_handler
            ::_pbi::TcParser::GenericFallback,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<::novonotes::audio_engine::v1alpha1::
                                           ResetStateRequest>(),  // to_prefetch
#endif  // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            {::_pbi::TcParser::MiniParse, {}},
        }},
        {{65535, 65535}},
        // no field_entries, or aux_entries
        {{}},
    };

::google::protobuf::Metadata ResetStateRequest::GetMetadata() const
{
    return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(
        GetClassData()->full());
}
// ===================================================================

class ResetStateResponse::_Internal
{
   public:
};

ResetStateResponse::ResetStateResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
    // @@protoc_insertion_point(arena_constructor:novonotes.audio_engine.v1alpha1.ResetStateResponse)
}
ResetStateResponse::ResetStateResponse(::google::protobuf::Arena* arena,
                                       const ResetStateResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
    ResetStateResponse* const _this = this;
    (void)_this;
    _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
        from._internal_metadata_);

    // @@protoc_insertion_point(copy_constructor:novonotes.audio_engine.v1alpha1.ResetStateResponse)
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ResetStateResponse::_class_data_ = {
        ::google::protobuf::internal::ZeroFieldsBase::ClassData{
            &_ResetStateResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ResetStateResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::internal::ZeroFieldsBase::GetDeleteImpl<
                ResetStateResponse>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<
                ResetStateResponse>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<
                ResetStateResponse>(),
            &ResetStateResponse::ByteSizeLong,
            &ResetStateResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ResetStateResponse, _impl_._cached_size_),
            false,
        },
        &ResetStateResponse::kDescriptorMethods,
        &descriptor_table_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto,
        nullptr,  // tracker
    };
const ::google::protobuf::MessageLite::ClassData*
ResetStateResponse::GetClassData() const
{
    ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
    ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
    return _class_data_.base();
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
    ResetStateResponse::_table_ = {
        {
            0,     // no _has_bits_
            0,     // no _extensions_
            0, 0,  // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967295,                                // skipmap
            offsetof(decltype(_table_), field_names),  // no field_entries
            0,                                         // num_field_entries
            0,                                         // num_aux_entries
            offsetof(decltype(_table_), field_names),  // no aux_entries
            _class_data_.base(),
            nullptr,                            // post_loop_handler
            ::_pbi::TcParser::GenericFallback,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<
                ::novonotes::audio_engine::v1alpha1::
                    ResetStateResponse>(),  // to_prefetch
#endif                                      // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            {::_pbi::TcParser::MiniParse, {}},
        }},
        {{65535, 65535}},
        // no field_entries, or aux_entries
        {{}},
    };

::google::protobuf::Metadata ResetStateResponse::GetMetadata() const
{
    return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(
        GetClassData()->full());
}
// ===================================================================

class PlayTestToneRequest::_Internal
{
   public:
};

PlayTestToneRequest::PlayTestToneRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
    // @@protoc_insertion_point(arena_constructor:novonotes.audio_engine.v1alpha1.PlayTestToneRequest)
}
PlayTestToneRequest::PlayTestToneRequest(::google::protobuf::Arena* arena,
                                         const PlayTestToneRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
    PlayTestToneRequest* const _this = this;
    (void)_this;
    _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
        from._internal_metadata_);

    // @@protoc_insertion_point(copy_constructor:novonotes.audio_engine.v1alpha1.PlayTestToneRequest)
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    PlayTestToneRequest::_class_data_ = {
        ::google::protobuf::internal::ZeroFieldsBase::ClassData{
            &_PlayTestToneRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &PlayTestToneRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::internal::ZeroFieldsBase::GetDeleteImpl<
                PlayTestToneRequest>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<
                PlayTestToneRequest>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<
                PlayTestToneRequest>(),
            &PlayTestToneRequest::ByteSizeLong,
            &PlayTestToneRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(PlayTestToneRequest, _impl_._cached_size_),
            false,
        },
        &PlayTestToneRequest::kDescriptorMethods,
        &descriptor_table_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto,
        nullptr,  // tracker
    };
const ::google::protobuf::MessageLite::ClassData*
PlayTestToneRequest::GetClassData() const
{
    ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
    ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
    return _class_data_.base();
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
    PlayTestToneRequest::_table_ = {
        {
            0,     // no _has_bits_
            0,     // no _extensions_
            0, 0,  // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967295,                                // skipmap
            offsetof(decltype(_table_), field_names),  // no field_entries
            0,                                         // num_field_entries
            0,                                         // num_aux_entries
            offsetof(decltype(_table_), field_names),  // no aux_entries
            _class_data_.base(),
            nullptr,                            // post_loop_handler
            ::_pbi::TcParser::GenericFallback,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<
                ::novonotes::audio_engine::v1alpha1::
                    PlayTestToneRequest>(),  // to_prefetch
#endif                                       // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            {::_pbi::TcParser::MiniParse, {}},
        }},
        {{65535, 65535}},
        // no field_entries, or aux_entries
        {{}},
    };

::google::protobuf::Metadata PlayTestToneRequest::GetMetadata() const
{
    return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(
        GetClassData()->full());
}
// ===================================================================

class PlayTestToneResponse::_Internal
{
   public:
};

PlayTestToneResponse::PlayTestToneResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
    // @@protoc_insertion_point(arena_constructor:novonotes.audio_engine.v1alpha1.PlayTestToneResponse)
}
PlayTestToneResponse::PlayTestToneResponse(::google::protobuf::Arena* arena,
                                           const PlayTestToneResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
    PlayTestToneResponse* const _this = this;
    (void)_this;
    _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
        from._internal_metadata_);

    // @@protoc_insertion_point(copy_constructor:novonotes.audio_engine.v1alpha1.PlayTestToneResponse)
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    PlayTestToneResponse::_class_data_ = {
        ::google::protobuf::internal::ZeroFieldsBase::ClassData{
            &_PlayTestToneResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &PlayTestToneResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::internal::ZeroFieldsBase::GetDeleteImpl<
                PlayTestToneResponse>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<
                PlayTestToneResponse>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<
                PlayTestToneResponse>(),
            &PlayTestToneResponse::ByteSizeLong,
            &PlayTestToneResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(PlayTestToneResponse, _impl_._cached_size_),
            false,
        },
        &PlayTestToneResponse::kDescriptorMethods,
        &descriptor_table_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto,
        nullptr,  // tracker
    };
const ::google::protobuf::MessageLite::ClassData*
PlayTestToneResponse::GetClassData() const
{
    ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
    ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
    return _class_data_.base();
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
    PlayTestToneResponse::_table_ = {
        {
            0,     // no _has_bits_
            0,     // no _extensions_
            0, 0,  // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967295,                                // skipmap
            offsetof(decltype(_table_), field_names),  // no field_entries
            0,                                         // num_field_entries
            0,                                         // num_aux_entries
            offsetof(decltype(_table_), field_names),  // no aux_entries
            _class_data_.base(),
            nullptr,                            // post_loop_handler
            ::_pbi::TcParser::GenericFallback,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<
                ::novonotes::audio_engine::v1alpha1::
                    PlayTestToneResponse>(),  // to_prefetch
#endif                                        // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            {::_pbi::TcParser::MiniParse, {}},
        }},
        {{65535, 65535}},
        // no field_entries, or aux_entries
        {{}},
    };

::google::protobuf::Metadata PlayTestToneResponse::GetMetadata() const
{
    return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(
        GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1alpha1
}  // namespace audio_engine
}  // namespace novonotes
namespace google
{
namespace protobuf
{}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type _static_init2_
    PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(
             &descriptor_table_novonotes_2faudio_5fengine_2fv1alpha1_2fengine_5fmanagement_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
