// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/api/field_info.proto
// Protobuf C++ Version: 5.28.1

#include "google/api/field_info.pb.h"

#include <algorithm>
#include <type_traits>

#include "google/protobuf/descriptor.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/wire_format_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace google
{
namespace api
{

inline constexpr TypeReference::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
    : type_name_(&::google::protobuf::internal::fixed_address_empty_string,
                 ::_pbi::ConstantInitialized())
    , _cached_size_{0}
{}

template <typename>
PROTOBUF_CONSTEXPR TypeReference::TypeReference(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base())
    ,
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message()
    ,
#endif  // PROTOBUF_CUSTOM_VTABLE
    _impl_(::_pbi::ConstantInitialized())
{}
struct TypeReferenceDefaultTypeInternal
{
    PROTOBUF_CONSTEXPR TypeReferenceDefaultTypeInternal()
        : _instance(::_pbi::ConstantInitialized{})
    {}
    ~TypeReferenceDefaultTypeInternal() {}
    union
    {
        TypeReference _instance;
    };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TypeReferenceDefaultTypeInternal
        _TypeReference_default_instance_;

inline constexpr FieldInfo::Impl_::Impl_(::_pbi::ConstantInitialized) noexcept
    : referenced_types_{}
    , format_{static_cast<::google::api::FieldInfo_Format>(0)}
    , _cached_size_{0}
{}

template <typename>
PROTOBUF_CONSTEXPR FieldInfo::FieldInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base())
    ,
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message()
    ,
#endif  // PROTOBUF_CUSTOM_VTABLE
    _impl_(::_pbi::ConstantInitialized())
{}
struct FieldInfoDefaultTypeInternal
{
    PROTOBUF_CONSTEXPR FieldInfoDefaultTypeInternal()
        : _instance(::_pbi::ConstantInitialized{})
    {}
    ~FieldInfoDefaultTypeInternal() {}
    union
    {
        FieldInfo _instance;
    };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FieldInfoDefaultTypeInternal
        _FieldInfo_default_instance_;
}  // namespace api
}  // namespace google
static const ::_pb::EnumDescriptor*
    file_level_enum_descriptors_google_2fapi_2ffield_5finfo_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_google_2fapi_2ffield_5finfo_2eproto =
        nullptr;
const ::uint32_t TableStruct_google_2fapi_2ffield_5finfo_2eproto::offsets
    [] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::google::api::FieldInfo, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::google::api::FieldInfo, _impl_.format_),
        PROTOBUF_FIELD_OFFSET(::google::api::FieldInfo,
                              _impl_.referenced_types_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::google::api::TypeReference,
                              _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::google::api::TypeReference, _impl_.type_name_),
};

static const ::_pbi::MigrationSchema schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    {0, -1, -1, sizeof(::google::api::FieldInfo)},
    {10, -1, -1, sizeof(::google::api::TypeReference)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::google::api::_FieldInfo_default_instance_._instance,
    &::google::api::_TypeReference_default_instance_._instance,
};
const char descriptor_table_protodef_google_2fapi_2ffield_5finfo_2eproto
    [] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        "\n\033google/api/field_info.proto\022\ngoogle.ap"
        "i\032 google/protobuf/descriptor.proto\"\301\001\n\t"
        "FieldInfo\022,\n\006format\030\001 \001(\0162\034.google.api.F"
        "ieldInfo.Format\0223\n\020referenced_types\030\002 \003("
        "\0132\031.google.api.TypeReference\"Q\n\006Format\022\026"
        "\n\022FORMAT_"
        "UNSPECIFIED\020\000\022\t\n\005UUID4\020\001\022\010\n\004IPV"
        "4\020\002\022\010\n\004IPV6\020\003\022\020\n\014IPV4_OR_"
        "IPV6\020\004\"\"\n\rTypeR"
        "eference\022\021\n\ttype_name\030\001 \001(\t:L\n\nfield_inf"
        "o\022\035.google.protobuf.FieldOptions\030\314\361\371\212\001 \001"
        "(\0132\025.google.api.FieldInfoBl\n\016com.google."
        "apiB\016FieldInfoProtoP\001ZAgoogle.golang.org"
        "/genproto/googleapis/api/annotations;ann"
        "otations\242\002\004GAPIb\006proto3"};
static const ::_pbi::DescriptorTable* const
    descriptor_table_google_2fapi_2ffield_5finfo_2eproto_deps[1] = {
        &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::absl::once_flag
    descriptor_table_google_2fapi_2ffield_5finfo_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable
    descriptor_table_google_2fapi_2ffield_5finfo_2eproto = {
        false,
        false,
        503,
        descriptor_table_protodef_google_2fapi_2ffield_5finfo_2eproto,
        "google/api/field_info.proto",
        &descriptor_table_google_2fapi_2ffield_5finfo_2eproto_once,
        descriptor_table_google_2fapi_2ffield_5finfo_2eproto_deps,
        1,
        2,
        schemas,
        file_default_instances,
        TableStruct_google_2fapi_2ffield_5finfo_2eproto::offsets,
        file_level_enum_descriptors_google_2fapi_2ffield_5finfo_2eproto,
        file_level_service_descriptors_google_2fapi_2ffield_5finfo_2eproto,
};
namespace google
{
namespace api
{
const ::google::protobuf::EnumDescriptor* FieldInfo_Format_descriptor()
{
    ::google::protobuf::internal::AssignDescriptors(
        &descriptor_table_google_2fapi_2ffield_5finfo_2eproto);
    return file_level_enum_descriptors_google_2fapi_2ffield_5finfo_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t FieldInfo_Format_internal_data_[] = {
    327680u,
    0u,
};
bool FieldInfo_Format_IsValid(int value) { return 0 <= value && value <= 4; }
#if (__cplusplus < 201703) && \
    (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr FieldInfo_Format FieldInfo::FORMAT_UNSPECIFIED;
constexpr FieldInfo_Format FieldInfo::UUID4;
constexpr FieldInfo_Format FieldInfo::IPV4;
constexpr FieldInfo_Format FieldInfo::IPV6;
constexpr FieldInfo_Format FieldInfo::IPV4_OR_IPV6;
constexpr FieldInfo_Format FieldInfo::Format_MIN;
constexpr FieldInfo_Format FieldInfo::Format_MAX;
constexpr int FieldInfo::Format_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class FieldInfo::_Internal
{
   public:
};

FieldInfo::FieldInfo(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
    SharedCtor(arena);
    // @@protoc_insertion_point(arena_constructor:google.api.FieldInfo)
}
inline PROTOBUF_NDEBUG_INLINE FieldInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena, const Impl_& from,
    const ::google::api::FieldInfo& from_msg)
    : referenced_types_{visibility, arena, from.referenced_types_}
    , _cached_size_{0}
{}

FieldInfo::FieldInfo(::google::protobuf::Arena* arena, const FieldInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
    FieldInfo* const _this = this;
    (void)_this;
    _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
        from._internal_metadata_);
    new(&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
    _impl_.format_ = from._impl_.format_;

    // @@protoc_insertion_point(copy_constructor:google.api.FieldInfo)
}
inline PROTOBUF_NDEBUG_INLINE FieldInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
    : referenced_types_{visibility, arena}
    , _cached_size_{0}
{}

inline void FieldInfo::SharedCtor(::_pb::Arena* arena)
{
    new(&_impl_) Impl_(internal_visibility(), arena);
    _impl_.format_ = {};
}
FieldInfo::~FieldInfo()
{
    // @@protoc_insertion_point(destructor:google.api.FieldInfo)
    _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
    SharedDtor();
}
inline void FieldInfo::SharedDtor()
{
    ABSL_DCHECK(GetArena() == nullptr);
    _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull FieldInfo::_class_data_ = {
    ::google::protobuf::Message::ClassData{
        &_FieldInfo_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &FieldInfo::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::google::protobuf::Message::GetDeleteImpl<FieldInfo>(),
        ::google::protobuf::Message::GetNewImpl<FieldInfo>(),
        ::google::protobuf::Message::GetClearImpl<FieldInfo>(),
        &FieldInfo::ByteSizeLong,
        &FieldInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(FieldInfo, _impl_._cached_size_),
        false,
    },
    &FieldInfo::kDescriptorMethods,
    &descriptor_table_google_2fapi_2ffield_5finfo_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* FieldInfo::GetClassData()
    const
{
    ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
    ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
    return _class_data_.base();
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<1, 2, 1, 0, 2>
    FieldInfo::_table_ = {
        {
            0,     // no _has_bits_
            0,     // no _extensions_
            2, 8,  // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967292,  // skipmap
            offsetof(decltype(_table_), field_entries),
            2,  // num_field_entries
            1,  // num_aux_entries
            offsetof(decltype(_table_), aux_entries), _class_data_.base(),
            nullptr,                            // post_loop_handler
            ::_pbi::TcParser::GenericFallback,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<
                ::google::api::FieldInfo>(),  // to_prefetch
#endif                                        // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            // repeated .google.api.TypeReference referenced_types = 2;
            {::_pbi::TcParser::FastMtR1,
             {18, 63, 0,
              PROTOBUF_FIELD_OFFSET(FieldInfo, _impl_.referenced_types_)}},
            // .google.api.FieldInfo.Format format = 1;
            {::_pbi::TcParser::SingularVarintNoZag1<
                 ::uint32_t, offsetof(FieldInfo, _impl_.format_), 63>(),
             {8, 63, 0, PROTOBUF_FIELD_OFFSET(FieldInfo, _impl_.format_)}},
        }},
        {{65535, 65535}},
        {{
            // .google.api.FieldInfo.Format format = 1;
            {PROTOBUF_FIELD_OFFSET(FieldInfo, _impl_.format_), 0, 0,
             (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
            // repeated .google.api.TypeReference referenced_types = 2;
            {PROTOBUF_FIELD_OFFSET(FieldInfo, _impl_.referenced_types_), 0, 0,
             (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
        }},
        {{
            {::_pbi::TcParser::GetTable<::google::api::TypeReference>()},
        }},
        {{}},
    };

PROTOBUF_NOINLINE void FieldInfo::Clear()
{
    // @@protoc_insertion_point(message_clear_start:google.api.FieldInfo)
    ::google::protobuf::internal::TSanWrite(&_impl_);
    ::uint32_t cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    _impl_.referenced_types_.Clear();
    _impl_.format_ = 0;
    _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* FieldInfo::_InternalSerialize(
    const MessageLite& base, ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream)
{
    const FieldInfo& this_ = static_cast<const FieldInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* FieldInfo::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const
{
    const FieldInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
        // @@protoc_insertion_point(serialize_to_array_start:google.api.FieldInfo)
    ::uint32_t cached_has_bits = 0;
    (void)cached_has_bits;

    // .google.api.FieldInfo.Format format = 1;
    if(this_._internal_format() != 0)
    {
        target = stream->EnsureSpace(target);
        target = ::_pbi::WireFormatLite::WriteEnumToArray(
            1, this_._internal_format(), target);
    }

    // repeated .google.api.TypeReference referenced_types = 2;
    for(unsigned i = 0, n = static_cast<unsigned>(
                            this_._internal_referenced_types_size());
        i < n; i++)
    {
        const auto& repfield = this_._internal_referenced_types().Get(i);
        target =
            ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, repfield, repfield.GetCachedSize(), target, stream);
    }

    if(PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields()))
    {
        target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_
                .unknown_fields<::google::protobuf::UnknownFieldSet>(
                    ::google::protobuf::UnknownFieldSet::default_instance),
            target, stream);
    }
    // @@protoc_insertion_point(serialize_to_array_end:google.api.FieldInfo)
    return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t FieldInfo::ByteSizeLong(const MessageLite& base)
{
    const FieldInfo& this_ = static_cast<const FieldInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t FieldInfo::ByteSizeLong() const
{
    const FieldInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
        // @@protoc_insertion_point(message_byte_size_start:google.api.FieldInfo)
    ::size_t total_size = 0;

    ::uint32_t cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    ::_pbi::Prefetch5LinesFrom7Lines(&this_);
    {
        // repeated .google.api.TypeReference referenced_types = 2;
        {
            total_size += 1UL * this_._internal_referenced_types_size();
            for(const auto& msg : this_._internal_referenced_types())
            {
                total_size +=
                    ::google::protobuf::internal::WireFormatLite::MessageSize(
                        msg);
            }
        }
    }
    {
        // .google.api.FieldInfo.Format format = 1;
        if(this_._internal_format() != 0)
        {
            total_size +=
                1 + ::_pbi::WireFormatLite::EnumSize(this_._internal_format());
        }
    }
    return this_.MaybeComputeUnknownFieldsSize(total_size,
                                               &this_._impl_._cached_size_);
}

void FieldInfo::MergeImpl(::google::protobuf::MessageLite& to_msg,
                          const ::google::protobuf::MessageLite& from_msg)
{
    auto* const _this = static_cast<FieldInfo*>(&to_msg);
    auto& from = static_cast<const FieldInfo&>(from_msg);
    // @@protoc_insertion_point(class_specific_merge_from_start:google.api.FieldInfo)
    ABSL_DCHECK_NE(&from, _this);
    ::uint32_t cached_has_bits = 0;
    (void)cached_has_bits;

    _this->_internal_mutable_referenced_types()->MergeFrom(
        from._internal_referenced_types());
    if(from._internal_format() != 0)
    {
        _this->_impl_.format_ = from._impl_.format_;
    }
    _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
        from._internal_metadata_);
}

void FieldInfo::CopyFrom(const FieldInfo& from)
{
    // @@protoc_insertion_point(class_specific_copy_from_start:google.api.FieldInfo)
    if(&from == this) return;
    Clear();
    MergeFrom(from);
}

void FieldInfo::InternalSwap(FieldInfo* PROTOBUF_RESTRICT other)
{
    using std::swap;
    _internal_metadata_.InternalSwap(&other->_internal_metadata_);
    _impl_.referenced_types_.InternalSwap(&other->_impl_.referenced_types_);
    swap(_impl_.format_, other->_impl_.format_);
}

::google::protobuf::Metadata FieldInfo::GetMetadata() const
{
    return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TypeReference::_Internal
{
   public:
};

TypeReference::TypeReference(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
    SharedCtor(arena);
    // @@protoc_insertion_point(arena_constructor:google.api.TypeReference)
}
inline PROTOBUF_NDEBUG_INLINE TypeReference::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena, const Impl_& from,
    const ::google::api::TypeReference& from_msg)
    : type_name_(arena, from.type_name_)
    , _cached_size_{0}
{}

TypeReference::TypeReference(::google::protobuf::Arena* arena,
                             const TypeReference& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base())
{
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena)
{
#endif  // PROTOBUF_CUSTOM_VTABLE
    TypeReference* const _this = this;
    (void)_this;
    _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
        from._internal_metadata_);
    new(&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

    // @@protoc_insertion_point(copy_constructor:google.api.TypeReference)
}
inline PROTOBUF_NDEBUG_INLINE TypeReference::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
    : type_name_(arena)
    , _cached_size_{0}
{}

inline void TypeReference::SharedCtor(::_pb::Arena* arena)
{
    new(&_impl_) Impl_(internal_visibility(), arena);
}
TypeReference::~TypeReference()
{
    // @@protoc_insertion_point(destructor:google.api.TypeReference)
    _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
    SharedDtor();
}
inline void TypeReference::SharedDtor()
{
    ABSL_DCHECK(GetArena() == nullptr);
    _impl_.type_name_.Destroy();
    _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    TypeReference::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_TypeReference_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &TypeReference::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<TypeReference>(),
            ::google::protobuf::Message::GetNewImpl<TypeReference>(),
            ::google::protobuf::Message::GetClearImpl<TypeReference>(),
            &TypeReference::ByteSizeLong,
            &TypeReference::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(TypeReference, _impl_._cached_size_),
            false,
        },
        &TypeReference::kDescriptorMethods,
        &descriptor_table_google_2fapi_2ffield_5finfo_2eproto,
        nullptr,  // tracker
    };
const ::google::protobuf::MessageLite::ClassData* TypeReference::GetClassData()
    const
{
    ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
    ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
    return _class_data_.base();
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<0, 1, 0, 42, 2>
    TypeReference::_table_ = {
        {
            0,     // no _has_bits_
            0,     // no _extensions_
            1, 0,  // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967294,  // skipmap
            offsetof(decltype(_table_), field_entries),
            1,                                         // num_field_entries
            0,                                         // num_aux_entries
            offsetof(decltype(_table_), field_names),  // no aux_entries
            _class_data_.base(),
            nullptr,                            // post_loop_handler
            ::_pbi::TcParser::GenericFallback,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<
                ::google::api::TypeReference>(),  // to_prefetch
#endif  // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            // string type_name = 1;
            {::_pbi::TcParser::FastUS1,
             {10, 63, 0,
              PROTOBUF_FIELD_OFFSET(TypeReference, _impl_.type_name_)}},
        }},
        {{65535, 65535}},
        {{
            // string type_name = 1;
            {PROTOBUF_FIELD_OFFSET(TypeReference, _impl_.type_name_), 0, 0,
             (0 | ::_fl::kFcSingular | ::_fl::kUtf8String |
              ::_fl::kRepAString)},
        }},
        // no aux_entries
        {{"\30\11\0\0\0\0\0\0"
          "google.api.TypeReference"
          "type_name"}},
    };

PROTOBUF_NOINLINE void TypeReference::Clear()
{
    // @@protoc_insertion_point(message_clear_start:google.api.TypeReference)
    ::google::protobuf::internal::TSanWrite(&_impl_);
    ::uint32_t cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    _impl_.type_name_.ClearToEmpty();
    _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* TypeReference::_InternalSerialize(
    const MessageLite& base, ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream)
{
    const TypeReference& this_ = static_cast<const TypeReference&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* TypeReference::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const
{
    const TypeReference& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
        // @@protoc_insertion_point(serialize_to_array_start:google.api.TypeReference)
    ::uint32_t cached_has_bits = 0;
    (void)cached_has_bits;

    // string type_name = 1;
    if(!this_._internal_type_name().empty())
    {
        const std::string& _s = this_._internal_type_name();
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            _s.data(), static_cast<int>(_s.length()),
            ::google::protobuf::internal::WireFormatLite::SERIALIZE,
            "google.api.TypeReference.type_name");
        target = stream->WriteStringMaybeAliased(1, _s, target);
    }

    if(PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields()))
    {
        target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_
                .unknown_fields<::google::protobuf::UnknownFieldSet>(
                    ::google::protobuf::UnknownFieldSet::default_instance),
            target, stream);
    }
    // @@protoc_insertion_point(serialize_to_array_end:google.api.TypeReference)
    return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t TypeReference::ByteSizeLong(const MessageLite& base)
{
    const TypeReference& this_ = static_cast<const TypeReference&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t TypeReference::ByteSizeLong() const
{
    const TypeReference& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
        // @@protoc_insertion_point(message_byte_size_start:google.api.TypeReference)
    ::size_t total_size = 0;

    ::uint32_t cached_has_bits = 0;
    // Prevent compiler warnings about cached_has_bits being unused
    (void)cached_has_bits;

    {
        // string type_name = 1;
        if(!this_._internal_type_name().empty())
        {
            total_size +=
                1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                        this_._internal_type_name());
        }
    }
    return this_.MaybeComputeUnknownFieldsSize(total_size,
                                               &this_._impl_._cached_size_);
}

void TypeReference::MergeImpl(::google::protobuf::MessageLite& to_msg,
                              const ::google::protobuf::MessageLite& from_msg)
{
    auto* const _this = static_cast<TypeReference*>(&to_msg);
    auto& from = static_cast<const TypeReference&>(from_msg);
    // @@protoc_insertion_point(class_specific_merge_from_start:google.api.TypeReference)
    ABSL_DCHECK_NE(&from, _this);
    ::uint32_t cached_has_bits = 0;
    (void)cached_has_bits;

    if(!from._internal_type_name().empty())
    {
        _this->_internal_set_type_name(from._internal_type_name());
    }
    _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
        from._internal_metadata_);
}

void TypeReference::CopyFrom(const TypeReference& from)
{
    // @@protoc_insertion_point(class_specific_copy_from_start:google.api.TypeReference)
    if(&from == this) return;
    Clear();
    MergeFrom(from);
}

void TypeReference::InternalSwap(TypeReference* PROTOBUF_RESTRICT other)
{
    using std::swap;
    auto* arena = GetArena();
    ABSL_DCHECK_EQ(arena, other->GetArena());
    _internal_metadata_.InternalSwap(&other->_internal_metadata_);
    ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.type_name_,
                                         &other->_impl_.type_name_, arena);
}

::google::protobuf::Metadata TypeReference::GetMetadata() const
{
    return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
    ::google::protobuf::FieldOptions,
    ::_pbi::MessageTypeTraits<::google::api::FieldInfo>, 11, false>
    field_info(kFieldInfoFieldNumber,
               &::google::api::_FieldInfo_default_instance_);
// @@protoc_insertion_point(namespace_scope)
}  // namespace api
}  // namespace google
namespace google
{
namespace protobuf
{}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type _static_init2_
    PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(
             &descriptor_table_google_2fapi_2ffield_5finfo_2eproto),
         ::_pbi::ExtensionSet::RegisterMessageExtension(
             &::google::protobuf::FieldOptions::default_instance(), 291403980,
             11, false, false, &::google::api::FieldInfo::default_instance(),
             nullptr, ::_pbi::LazyAnnotation::kUndefined),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
